'use client';

import { useEffect, useRef, useState } from 'react';

type Language = 'ja' | 'en' | 'pt';

const languages: Array<{ id: Language; label: string }> = [
  { id: 'ja', label: '日本語' },
  { id: 'en', label: 'English' },
  { id: 'pt', label: 'Português' },
];

const copy: Record<string, [string, string]> = {
  '温泉を守る': ['Save the Onsen', 'Salve o onsen'],
  '福井の未来': ['Fukui’s Future', 'Futuro de Fukui'],
  '福井に、': ['In Fukui,', 'Em Fukui,'],
  '何が残る？': ['what will remain?', 'o que permanecerá?'],
  'データセンターをつくることだけが目的ではありません。温泉を中心に、学び、農業、仕事、商い、文化がつながり、そこで働く人とプロジェクトが私たちのCOG DCコンピュートを使える土台を検証します。': ['Building a data center is not the only goal. We will test a foundation that connects learning, agriculture, work, commerce, and culture around the onsen, with our COG DC compute available to the people and projects working there.', 'Construir um data center não é o único objetivo. Vamos testar uma base que conecta aprendizagem, agricultura, trabalho, comércio e cultura ao redor do onsen, com nossa computação COG DC disponível às pessoas e aos projetos que trabalham ali.'],
  '8つの地域価値を見る': ['See eight forms of local value', 'Ver oito formas de valor local'],
  '計算機だけではない。': ['It is more than machines.', 'É mais do que máquinas.'],
  '地域に残る価値': ['It is value that remains here.', 'É valor que permanece aqui.'],
  '一つひとつは小さく始められます。大切なのは、別々の事業にせず、温泉を中心に人と仕事が循環する仕組みにすることです。': ['Each part can start small. What matters is connecting them so that people and work circulate around the onsen.', 'Cada parte pode começar pequena. O importante é conectá-las para que pessoas e trabalho circulem ao redor do onsen.'],
  '私たちのCOG DC': ['Our COG DC', 'Nosso COG DC'],
  'そこで働く人とプロジェクトが使えるコンピュートをつくる。': ['Produce compute for the people and projects working there.', 'Produzir computação para as pessoas e os projetos que trabalham ali.'],
  'COG DCの電力から、': ['From COG DC energy', 'Da energia do COG DC'],
  '福井の仕事へ。': ['to work in Fukui.', 'ao trabalho em Fukui.'],
  'COG DCから福井の地域経済へつながる流れ': ['How COG DC connects to Fukui’s economy', 'Como o COG DC se conecta à economia de Fukui'],
  '私たちのCOG DCコンピュート': ['Our COG DC compute', 'Nossa computação COG DC'],
  '学生・FoundUps': ['Students and FoundUps', 'Estudantes e FoundUps'],
  '解決策と仕事': ['Solutions and work', 'Soluções e trabalho'],
  'すべての仕事やデータを地域内に限定するという意味ではありません。COG DCで働く人とプロジェクトが、計算、モデル、知識、適切に管理されたデータを使い、福井の実課題に取り組める選択肢を増やします。': ['This does not mean confining all work or data locally. It expands the options for people and projects working at the COG DC to use compute, models, knowledge, and properly governed data on real Fukui problems.', 'Isso não significa limitar todo trabalho ou dado ao âmbito local. Amplia as opções para pessoas e projetos no COG DC usarem computação, modelos, conhecimento e dados bem governados em problemas reais de Fukui.'],
  '段階的な検証': ['Step-by-step validation', 'Validação por etapas'],
  '需要を確認': ['Validate demand', 'Validar demanda'],
  '学生、FoundUps、研究、地域プロジェクトが何を使うかを具体化します。': ['Define what students, FoundUps, research, and community projects will actually use.', 'Definir o que estudantes, FoundUps, pesquisa e projetos comunitários realmente usarão.'],
  '工学を確認': ['Validate engineering', 'Validar engenharia'],
  '電力、通信、冷却、安全、別棟配置、回収熱の温度と距離を調べます。': ['Study power, network, cooling, safety, the separate-site layout, and recoverable heat temperature and distance.', 'Estudar energia, rede, refrigeração, segurança, implantação separada e temperatura e distância do calor recuperável.'],
  '経済性を確認': ['Validate economics', 'Validar economia'],
  '設備費、運営費、利用契約、熱利用の価値を実測・見積もりで比べます。': ['Compare equipment, operating costs, use agreements, and heat value with measurements and quotations.', 'Comparar equipamentos, custos operacionais, contratos de uso e valor térmico com medições e cotações.'],
  '約1 MWから': ['Start around 1 MW', 'Começar em cerca de 1 MW'],
  '契約・許認可済み容量ではなく、最初の検証規模です。': ['An initial validation scale—not contracted or permitted capacity.', 'Uma escala inicial de validação — não capacidade contratada nem licenciada.'],
  '利用が育った時だけ': ['Only when use grows', 'Somente quando o uso crescer'],
  '電力、許認可、資金、土地、需要、地域合意がそろってから拡張を判断します。': ['Consider expansion only after power, permits, funding, land, demand, and community agreement align.', 'Considerar expansão somente quando energia, licenças, financiamento, terreno, demanda e acordo comunitário estiverem alinhados.'],
  '容量、時期、費用、熱利用、収益は未確定です。調査と関係者合意なしに建設を約束しません。': ['Capacity, timing, cost, heat use, and revenue are undecided. Construction is not promised without studies and stakeholder agreement.', 'Capacidade, prazo, custo, uso do calor e receita não estão definidos. Não se promete construção sem estudos e acordo das partes.'],
  'AI拠点': ['AI Hub', 'Polo de IA'],
  '温泉を守る · 福井の選択': ['SAVE THE ONSEN · FUKUI’S CHOICE', 'SALVE O ONSEN · A ESCOLHA DE FUKUI'],
  '九頭竜を守るための行動メニュー': ['Actions to save Kuzuryu', 'Ações para salvar Kuzuryu'],
  'YUMORI / COG DC 10枚のプレゼンを見る': ['See the new YUMORI / COG DC presentation', 'Veja a nova apresentação YUMORI / COG DC'],
  '写真で現地を見る': ['See the site in photos', 'Ver o local em fotos'],
  '九頭竜の音楽を聴く': ['Listen to the music of Kuzuryu', 'Ouvir a música de Kuzuryu'],
  '再生計画を読む': ['Read the renewal plan', 'Ler o plano de renovação'],
  'YUMORI.infoでプロジェクトを見る': ['Explore the project on YUMORI.info', 'Explorar o projeto no YUMORI.info'],
  'Monkとつながる': ['Connect with the Monk', 'Conectar-se com o Monk'],
  '温泉を守る準備委員会に名前を加える': ['Add your name to the Save Onsen Preparatory Committee', 'Adicione seu nome ao Comitê Preparatório Save Onsen'],
  '福井市役所へ声を届ける': ['Contact Fukui City Hall', 'Entrar em contato com a Prefeitura de Fukui'],
  '九頭竜を守れ。温泉を守れ。': ['Save Kuzuryu. Save the onsen.', 'Salve Kuzuryu. Salve o onsen.'],
  '見る。知る。共有する。': ['See it. Learn. Share.', 'Veja. Conheça. Compartilhe.'],
  'そして、動く。': ['Then take action.', 'Depois, aja.'],
  '九頭竜を守るために、今できることを一つ選んでください。温泉を残す力は、一人ひとりの声から始まります。': ['Choose one thing you can do now to help save Kuzuryu. Saving the onsen begins with each person’s voice.', 'Escolha uma ação que você pode realizar agora para ajudar a salvar Kuzuryu. Salvar o onsen começa com a voz de cada pessoa.'],
  '九頭竜を守るために今できること': ['Actions you can take now to save Kuzuryu', 'Ações que você pode realizar agora para salvar Kuzuryu'],
  '現地と構想を見る': ['See the site and the vision', 'Ver o local e a visão'],
  '写真で、建物、土地、地域の記憶を確かめる。': ['See the building, the land, and community memories in photographs.', 'Veja em fotografias o edifício, o terreno e as memórias da comunidade.'],
  '九頭竜と温泉再生の物語を、0102 MUSICで感じる。': ['Experience the story of Kuzuryu and the onsen’s renewal through 0102 MUSIC.', 'Sinta a história de Kuzuryu e da renovação do onsen com 0102 MUSIC.'],
  '再生計画を知る': ['Understand the renewal plan', 'Conhecer o plano de renovação'],
  'COG DC、温泉、教育、食、文化をつなぐ計画を読む。': ['Read how the plan connects our COG DC, the onsen, education, food, and culture.', 'Leia como o plano conecta nosso COG DC, onsen, educação, gastronomia e cultura.'],
  '家族や友人に共有する': ['Share with family and friends', 'Compartilhar com familiares e amigos'],
  'yumori.infoを送り、九頭竜の未来を話題にする。': ['Send yumori.info and start a conversation about Kuzuryu’s future.', 'Envie yumori.info e inicie uma conversa sobre o futuro de Kuzuryu.'],
  'yumori.infoを共有': ['Share yumori.info', 'Compartilhar yumori.info'],
  '市民宣言に参加する': ['Join the citizens’ declaration', 'Participar da declaração cidadã'],
  '解体前に代案を比べる機会を残す意思を伝える。': ['Say that alternatives should be compared before demolition.', 'Declare que as alternativas devem ser comparadas antes da demolição.'],
  '福井市役所に、': ['To Fukui City Hall,', 'À Prefeitura de Fukui,'],
  '声を届ける。': ['make your voice heard.', 'faça sua voz ser ouvida.'],
  '旧すかっとランド九頭竜の公式問い合わせ先は、福井市 福祉健康部 地域包括ケア推進課です。': ['The official City contact for the former Sukatto Land Kuzuryu is Fukui City’s Community Comprehensive Care Promotion Division.', 'O contato oficial da cidade para o antigo Sukatto Land Kuzuryu é a Divisão de Promoção de Cuidados Comunitários Integrados de Fukui.'],
  '電話する': ['Call', 'Ligar'],
  'メールで伝える': ['Send a message', 'Enviar mensagem'],
  '福井市公式フォーム ↗': ['Official Fukui City form ↗', 'Formulário oficial da Prefeitura de Fukui ↗'],
  '受付：平日 8:30–17:15': ['Hours: weekdays, 8:30–17:15', 'Horário: dias úteis, 8h30–17h15'],
  '伝える言葉の例': ['Suggested wording', 'Sugestão de mensagem'],
  '「旧すかっとランド九頭竜について、解体契約前に再利用案を公正に比較する機会を残してください。」': ['“For the former Sukatto Land Kuzuryu, please preserve an opportunity to fairly compare reuse proposals before a demolition contract is issued.”', '“Para o antigo Sukatto Land Kuzuryu, preserve a oportunidade de comparar de forma justa propostas de reutilização antes da contratação da demolição.”'],
  '共有画面を開きました': ['The share menu opened', 'O menu de compartilhamento foi aberto'],
  '共有リンクをコピーしました': ['The link was copied', 'O link foi copiado'],
  '共有できませんでした。yumori.infoをコピーしてください。': ['Could not share. Please copy yumori.info.', 'Não foi possível compartilhar. Copie yumori.info.'],
  'すかっとランド九頭竜は、解体に向けた手続きが進んでいます': ['The process toward demolishing Sukatto Land Kuzuryu is moving forward', 'O processo para demolir o Sukatto Land Kuzuryu está avançando'],
  '温泉を守り、': ['Save the Onsen.', 'Salve o onsen.'],
  '地域のAI基盤でまちを元気に。': ['Revitalize the Community with Local Compute.', 'Revitalize a comunidade com computação local.'],
  '私たちのCOG DCでまちを元気に。': ['Revitalize the community with our COG DC.', 'Revitalize a comunidade com o nosso COG DC.'],
  'COG DCの回収熱を、': ['Can recoverable heat from our COG DC', 'O calor recuperável do nosso COG DC pode'],
  '露天風呂へ活かせるか。': ['support the outdoor bath?', 'ajudar a aquecer o banho ao ar livre?'],
  '回収できる熱を温泉の補助加温に使えるか、温度、距離、年間需要、設備費を技術検証する構想です。': ['The proposal tests whether recoverable heat can supplement onsen heating by measuring temperature, distance, annual demand, and equipment cost.', 'A proposta testa se o calor recuperável pode complementar o aquecimento do onsen, medindo temperatura, distância, demanda anual e custo dos equipamentos.'],
  '夜は、D-Kによる': ['At night, propose D-K', 'À noite, propor o D-K'],
  '光の舞台を提案。': ['as a stage of light.', 'como um palco de luz.'],
  '建物を毎晩変化する光のキャンバスにする構想。長谷川章氏の参加は未承認で、現在は提案段階です。': ['The proposal turns the building into an ever-changing canvas of light. Akira Hasegawa has not committed; this remains a proposal.', 'A proposta transforma o edifício em uma tela de luz em constante mudança. Akira Hasegawa não confirmou participação; esta continua sendo uma proposta.'],
  '温泉・地域・教育': ['Onsen, community, and education', 'Onsen, comunidade e educação'],
  '温泉、公共利用、教育、展示、ロボティクス、イベント、来訪者との交流。': ['Onsen, public uses, education, exhibits, robotics, events, and visitor interaction.', 'Onsen, usos públicos, educação, exposições, robótica, eventos e interação com visitantes.'],
  '学生と初期FoundUps': ['Students and emerging FoundUps', 'Estudantes e FoundUps emergentes'],
  '選抜された学生と若いチームが、旧客室を小さなプロジェクトスタジオとして使い、実課題を解く。': ['Selected students and young teams use former guest rooms as small project studios to solve real problems.', 'Estudantes selecionados e equipes jovens usam antigos quartos como pequenos estúdios de projeto para resolver problemas reais.'],
  '検証されたFoundUps': ['Validated FoundUps', 'FoundUps validados'],
  '実用性、実行力、現実の価値を示したプロジェクトが上階へ進み、独立したAIネイティブ事業を目指す。': ['Projects that prove usefulness, execution, and real-world value move upward toward independent AI-native businesses.', 'Projetos que demonstram utilidade, execução e valor real avançam para se tornar negócios independentes nativos de IA.'],
  '建物とは別に配置し、そこで働く人とプロジェクトへCOG DCコンピュートを提供する構想。': ['A separate facility proposed to provide COG DC compute to the people and projects working there.', 'Uma instalação separada proposta para fornecer computação COG DC às pessoas e aos projetos que trabalham ali.'],
  '私たちのComputeが、': ['Our compute powers', 'Nossa computação impulsiona'],
  '福井には、AIを学ぶ大学、スマート農業、県民衛星、世界に誇るものづくりがすでにあります。私たちのCOG DCコンピュートは、そこで働く人とプロジェクトが、それらをつなぎ、試し、育てるための基盤です。': ['Fukui already has AI education, smart agriculture, a prefectural satellite, and world-class manufacturing. Our COG DC compute is a foundation for the people and projects working there to connect, test, and grow them.', 'Fukui já tem educação em IA, agricultura inteligente, um satélite provincial e manufatura de classe mundial. Nossa computação COG DC é uma base para as pessoas e projetos que trabalham ali conectarem, testarem e desenvolverem essas capacidades.'],
  '福井大学や福井県立大学では、データサイエンス・AI教育がすでに進んでいます。私たちのCOG DCコンピュートで、授業を実験と研究へ。': ['The University of Fukui and Fukui Prefectural University already advance data-science and AI education. Our COG DC compute can turn classes into experiments and research.', 'A Universidade de Fukui e a Universidade Provincial de Fukui já avançam no ensino de ciência de dados e IA. Nossa computação COG DC pode transformar aulas em experimentos e pesquisa.'],
  '繊維、眼鏡、機械、電子部品。私たちのCOG DCコンピュートで、設計、検査、自動化、新製品開発を支える。': ['Textiles, eyewear, machinery, and electronics: our COG DC compute can support design, inspection, automation, and product development.', 'Têxteis, óculos, máquinas e eletrônicos: nossa computação COG DC pode apoiar projeto, inspeção, automação e desenvolvimento de produtos.'],
  '未来を動かすのは、': ['The future is powered by', 'O futuro é impulsionado por'],
  '私たちのCOG DC Compute。': ['our COG DC compute.', 'nossa computação COG DC.'],
  '電力 → COG DC → プロジェクト → 福井の未来。': ['Energy → COG DC → projects → Fukui’s future.', 'Energia → COG DC → projetos → futuro de Fukui.'],
  'この施設が農機を直接動かすわけではありません。私たちのCOG DCコンピュートを、そこで働く学生、FoundUps、研究・地域プロジェクトが使い、農業AI、教育、研究、ものづくりの開発と検証を支えます。': ['The facility does not directly operate farm machinery. Students, FoundUps, researchers, and community projects working there use our COG DC compute to develop and test agricultural AI, education, research, and manufacturing applications.', 'A instalação não opera máquinas agrícolas diretamente. Estudantes, FoundUps, pesquisadores e projetos comunitários que trabalham ali usam nossa computação COG DC para desenvolver e testar aplicações em IA agrícola, educação, pesquisa e manufatura.'],
  '電力 → 私たちのCOG DCコンピュート → 解決策 → 福井の仕事': ['Energy → our COG DC compute → solutions → work in Fukui', 'Energia → nossa computação COG DC → soluções → trabalho em Fukui'],
  'WHY · 温泉を守る': ['WHY · SAVE THE ONSEN', 'POR QUÊ · SALVAR O ONSEN'],
  'HOW · ESINGULARITY INNOVATION HUB': ['HOW · ESINGULARITY INNOVATION HUB', 'COMO · ESINGULARITY INNOVATION HUB'],
  'WHEN · COMMUNITY MEETINGS': ['WHEN · COMMUNITY MEETINGS', 'QUANDO · ENCONTROS COMUNITÁRIOS'],
  '壊すために公費を使う前に、この建物で福井の未来をつくろう。温泉を再開する。学びと起業の拠点をつくる。地域のコンピュートの熱を、地域へ返す。': ['Before spending public money to demolish this place, let’s use it to build Fukui’s future. Reopen the onsen. Create a home for learning and startups. Return heat from local compute to the community.', 'Antes de gastar dinheiro público para demolir este lugar, vamos usá-lo para construir o futuro de Fukui. Reabrir o onsen. Criar um espaço para aprendizagem e startups. Devolver à comunidade o calor da computação local.'],
  '壊すために公費を使う前に、この建物で福井の未来をつくろう。温泉を再開する。学びと起業の拠点をつくる。私たちのCOG DCから回収できる熱を、地域へ返せるか検証する。': ['Before spending public money to demolish this place, use it to build Fukui’s future: reopen the onsen, create a home for learning and ventures, and test whether recoverable heat from our COG DC can serve the community.', 'Antes de gastar dinheiro público para demolir este lugar, use-o para construir o futuro de Fukui: reabrir o onsen, criar um espaço de aprendizagem e empreendimentos e testar se o calor recuperável do nosso COG DC pode servir à comunidade.'],
  'WHAT · ここがどう変わる？': ['WHAT · WHAT WILL THIS BECOME?', 'O QUÊ · O QUE ESTE LUGAR PODE SE TORNAR?'],
  '温泉を残す。': ['Keep the onsen.', 'Preservar o onsen.'],
  '夜まで人が集まる場所': ['Build a place people visit into the night.', 'Criar um lugar onde as pessoas se reúnem até a noite.'],
  'をつくる。': ['', ''],
  '保存するだけではありません。温泉、地域の食、小さな商い、学び、光の文化を一つの場所につなぐ構想です。': ['This is more than preservation. The vision connects the onsen, local food, small businesses, learning, and a culture of light in one place.', 'É mais do que preservação. A visão conecta o onsen, comida local, pequenos negócios, aprendizagem e uma cultura de luz em um só lugar.'],
  '既存の南北に長い建物と南端の曲線棟、駐車場を残し、南側に露天風呂を加えた再生構想イメージ': ['Concept image preserving the existing long north–south building, connected curved southern wing, and parking while adding an outdoor bath to the south', 'Imagem conceitual que preserva o edifício existente alongado no sentido norte–sul, a ala curva conectada ao sul e o estacionamento, acrescentando um banho ao ar livre ao sul'],
  '現時点の構想イメージです。実際の配置・規模・熱利用は、建物・設備・法令・事業性の調査で決まります。': ['This is a concept image. Final layout, scale, and heat use depend on building, engineering, regulatory, and commercial studies.', 'Esta é uma imagem conceitual. O layout, a escala e o uso do calor dependerão de estudos do edifício, de engenharia, regulatórios e comerciais.'],
  '日本初を目指す、': ['Aiming to create Japan’s first', 'Com o objetivo de criar o primeiro do Japão'],
  'コンピュート排熱の露天風呂。': ['rotenburo warmed by recovered compute heat.', 'rotenburo aquecido com calor recuperado da computação.'],
  '回収できる熱を片側の露天風呂に集中し、男女どちらの湯を温めるかを日替わりでシステムが案内する構想です。': ['The concept directs available heat to one side of the rotenburo at a time, with the system announcing which bath is heated that day.', 'O conceito direciona o calor disponível para um lado do rotenburo por vez, com o sistema informando qual banho será aquecido naquele dia.'],
  'あわら型の、': ['An Awara-inspired', 'Um yokocho inspirado em Awara'],
  '小さなコンテナ横丁。': ['small container yokocho.', 'feito com pequenos contêineres.'],
  'あわら温泉の横丁型モデルに着想を得て、地域の料理人、農家、学生が小さく商いを始められる場所へ。': ['Inspired by Awara Onsen’s yokocho model: a place where local cooks, farmers, and students can start small businesses.', 'Inspirado no modelo yokocho de Awara Onsen: um lugar onde cozinheiros, agricultores e estudantes locais podem começar pequenos negócios.'],
  '実例を見る：あわら温泉「湯けむり横丁」↗': ['See the real example: Awara Onsen Yukemuri Yokocho ↗', 'Veja o exemplo real: Yukemuri Yokocho, em Awara Onsen ↗'],
  '夜は、長谷川章氏の': ['At night, Akira Hasegawa’s', 'À noite, a obra de Akira Hasegawa'],
  'D-Kという光の舞台へ。': ['D-K turns the site into a stage of light.', 'D-K transforma o local em um palco de luz.'],
  '建物を毎晩変化する光のキャンバスにする構想。九頭竜の水と龍を、地域の新しい夜景にします。': ['The vision makes the building an ever-changing canvas of light, turning Kuzuryu’s water and dragon into a new local nightscape.', 'A visão transforma o edifício em uma tela de luz em constante mudança, levando a água e o dragão de Kuzuryu a uma nova paisagem noturna local.'],
  'D-K公式ギャラリーを開く ↗': ['Open the official D-K gallery ↗', 'Abrir a galeria oficial do D-K ↗'],
  '長谷川章氏とD-Kの作品を見る': ['See Akira Hasegawa and his D-K works', 'Conheça Akira Hasegawa e suas obras D-K'],
  '温泉とコミュニティ空間': ['Onsen and Community Space', 'Onsen e espaço comunitário'],
  '温泉、大きな露天風呂、あわら型コンテナ・フードコート。': ['Onsen, a large rotenburo, and an Awara-inspired container food court.', 'Onsen, um grande rotenburo e uma praça de alimentação em contêineres inspirada em Awara.'],
  '地域の課題を通じて、研究と実践をつなぐ場所。': ['A place connecting research and practice through local challenges.', 'Um lugar que conecta pesquisa e prática por meio dos desafios locais.'],
  '研究を試し、福井の新しい仕事へ育てる場所。': ['A place to test research and grow it into new work in Fukui.', 'Um lugar para testar pesquisas e transformá-las em novos trabalhos em Fukui.'],
  'LINEで仲間になる': ['Join us on LINE', 'Junte-se a nós no LINE'],
  '計画を見る': ['See the plan', 'Veja o plano'],
  '思い出を守る。': ['Protect the memories.', 'Proteja as memórias.'],
  '012の温泉の記憶を読む →': ['Read 012’s onsen memory →', 'Leia a memória de 012 no onsen →'],
  '温泉の上に、': ['Above the onsen,', 'Acima do onsen,'],
  '福井の「学ぶ・創る・始める」': ['build Fukui’s place to learn, create and launch.', 'criar o lugar de Fukui para aprender, criar e lançar.'],
  'を重ねる。': ['', ''],
  '1階の温泉を地域の居場所として再開し、その上を世代ごとの学び、研究、起業がつながる場所へ。これは現時点の構想であり、建物調査と地域・所有者との合意を経て具体化します。': ['Reopen the first-floor onsen as a community gathering place. Above it, connect learning, research, and entrepreneurship across generations. This is a current concept to be refined through a building survey and agreements with the community and owners.', 'Reabrir o onsen do primeiro andar como ponto de encontro da comunidade. Acima dele, conectar aprendizado, pesquisa e empreendedorismo entre gerações. Este é um conceito atual, a ser definido após vistoria do edifício e acordos com a comunidade e os proprietários.'],
  'お米': ['Rice', 'Arroz'],
  '人のごはん': ['Food for people', 'Alimento das pessoas'],
  '人': ['People', 'Pessoas'],
  'AIのごはん': ['Food for AI', 'Alimento da IA'],
  '温泉と地域の居場所': ['Onsen and community space', 'Onsen e espaço comunitário'],
  '温泉を再開し、世代を超えて人が集まる入口に。': ['Reopen the onsen as a gateway where generations gather.', 'Reabrir o onsen como uma porta de entrada onde gerações se encontram.'],
  'AI学習スタジオ（小・中学生）': ['AI Learning Studio — Primary and Middle School', 'Estúdio de aprendizagem de IA — Ensino fundamental'],
  '保護者と先生が見守る中で、子どもたちがAIの仕組みを安全に学び、対話し、一緒に創る場所。': ['A parent- and teacher-guided studio where children can safely learn how AI works, interact with it, and create alongside it.', 'Um estúdio acompanhado por pais e professores, onde as crianças podem aprender com segurança como a IA funciona, interagir com ela e criar ao seu lado.'],
  'AI創造ラボ（高校生・大学生）': ['AI Creation Lab — High School and University', 'Laboratório de criação com IA — Ensino médio e universidade'],
  'AIと協働し、地域の課題を研究し、実践的な解決策を生み出す場所。': ['A place where students collaborate with AI to research local and regional challenges and develop practical solutions.', 'Um lugar onde estudantes colaboram com a IA para pesquisar desafios locais e regionais e desenvolver soluções práticas.'],
  'AIローンチ・ハブ（大学プロジェクト・スタートアップ）': ['AI Launch Hub — University Projects and Startups', 'Polo de lançamento com IA — Projetos universitários e startups'],
  'AIを活用した研究とアイデアを、福井の新しいプロジェクト、起業、仕事へ育てる場所。': ['A place to turn AI-assisted research and ideas into new projects, startups, and work in Fukui.', 'Um lugar para transformar pesquisas e ideias apoiadas por IA em novos projetos, startups e trabalho em Fukui.'],
  '構想図：階ごとの利用方法は、耐震・設備・消防・法令調査と関係者協議により変更されます。': ['Concept: floor uses may change after structural, equipment, fire-safety and legal reviews and consultation with stakeholders.', 'Conceito: o uso dos andares poderá mudar após análises estruturais, de instalações, segurança contra incêndio e legislação, além de consultas às partes envolvidas.'],
  'Computeが、': ['Compute Powers', 'A computação impulsiona'],
  '福井を動かす。': ['Fukui.', 'Fukui.'],
  '福井には、AIを学ぶ大学、スマート農業、県民衛星、世界に誇るものづくりがすでにあります。地域の計算力は、それらをつなぎ、試し、育てる基盤です。': ['Fukui already has AI education, smart agriculture, its own satellite, and world-class manufacturing. Local compute is the infrastructure that helps connect, test, and grow them.', 'Fukui já conta com educação em IA, agricultura inteligente, seu próprio satélite e uma indústria reconhecida mundialmente. A computação local é a infraestrutura que ajuda a conectar, testar e desenvolver tudo isso.'],
  '福井の学生と大学': ['Fukui’s students and universities', 'Estudantes e universidades de Fukui'],
  '福井大学や福井県立大学では、データサイエンス・AI教育がすでに進んでいます。地域の計算力で、授業を実験と研究へ。': ['The University of Fukui and Fukui Prefectural University are already advancing data-science and AI education. Local compute can turn lessons into experiments and research.', 'A Universidade de Fukui e a Universidade Provincial de Fukui já avançam no ensino de ciência de dados e IA. A computação local pode transformar aulas em experimentos e pesquisa.'],
  '福井大学 AI教育研究センター': ['University of Fukui AI Center', 'Centro de IA da Universidade de Fukui'],
  '福井の田んぼ': ['Fukui’s rice fields', 'Os arrozais de Fukui'],
  '自動走行農機、ロボット草刈機、収量計測、センシングドローン。福井の農業を、福井のAIで支える。': ['Autonomous farm machinery, robotic mowers, yield measurement, and sensing drones—supporting Fukui agriculture with AI developed in Fukui.', 'Máquinas agrícolas autônomas, cortadores robóticos, medição de produtividade e drones de sensoriamento — apoiando a agricultura de Fukui com IA desenvolvida em Fukui.'],
  '福井県 スマート農業支援': ['Fukui Prefecture smart-agriculture support', 'Apoio à agricultura inteligente de Fukui'],
  '県民衛星「すいせん」': ['Prefectural satellite “Suisen”', 'Satélite provincial “Suisen”'],
  '福井は衛星をつくり、農地、森林、災害、文化財にデータを活用しています。次は、そのデータを地域で計算する力へ。': ['Fukui built a satellite and uses its data for farmland, forests, disasters, and cultural heritage. The next step is the local capacity to compute with that data.', 'Fukui construiu um satélite e usa seus dados em lavouras, florestas, desastres e patrimônio cultural. O próximo passo é ter capacidade local para processar esses dados.'],
  '福井県民衛星プロジェクト': ['Fukui Prefectural Satellite Project', 'Projeto do Satélite da Província de Fukui'],
  '福井のものづくり': ['Fukui manufacturing', 'Indústria de Fukui'],
  '繊維、眼鏡、機械、電子部品。地域の計算力で、設計、検査、自動化、新製品開発を加速する。': ['Textiles, eyewear, machinery, and electronic components. Local compute can accelerate design, inspection, automation, and new-product development.', 'Têxteis, óculos, máquinas e componentes eletrônicos. A computação local pode acelerar projeto, inspeção, automação e desenvolvimento de novos produtos.'],
  '福井県の技術と産業': ['Fukui technology and industry', 'Tecnologia e indústria de Fukui'],
  '福井の知識とデータを、福井で価値に変える。': ['Turn Fukui’s knowledge and data into value in Fukui.', 'Transformar o conhecimento e os dados de Fukui em valor dentro de Fukui.'],
  'すべてを地域だけに閉じるという意味ではありません。福井の組織が、計算、モデル、適切に管理されたデータを、より地域の管理下に置ける選択肢を増やします。': ['This does not mean closing everything off inside the region. It gives Fukui organizations more options to keep computing, models, and appropriately governed data under greater local control.', 'Isso não significa fechar tudo dentro da região. Significa oferecer às organizações de Fukui mais opções para manter computação, modelos e dados devidamente governados sob maior controle local.'],
  '未来を動かすのは、': ['The future runs on ', 'O futuro funciona com '],
  'Compute。': ['compute.', 'computação.'],
  '福井の電力 → 福井の計算力 → 福井の未来。': ['Fukui energy → Fukui compute → Fukui’s future.', 'Energia de Fukui → computação de Fukui → futuro de Fukui.'],
  '選択肢を比べる': ['COMPARE THE CHOICES', 'COMPARE AS ESCOLHAS'],
  '60秒でわかる計画': ['THE PLAN IN 60 SECONDS', 'O PLANO EM 60 SEGUNDOS'],
  '壊すだけではない。': ['Demolition is not the only choice.', 'Demolir não é a única escolha.'],
  'こう変えられる。': ['Here is what it can become.', 'Veja no que pode se transformar.'],
  'いま': ['Today', 'Hoje'],
  '選択': ['The choice', 'A escolha'],
  '私たちの提案': ['Our proposal', 'Nossa proposta'],
  '閉館した施設': ['Closed facility', 'Instalação fechada'],
  '解体に向けた手続きが進んでいます。': ['The demolition process is moving forward.', 'O processo de demolição está avançando.'],
  '解体する': ['Demolish it', 'Demolir'],
  'または': ['or', 'ou'],
  'もう一つの未来を比べる': ['Compare another future', 'Comparar outro futuro'],
  '温泉を中心に、地域の未来をつくる': ['Build a local future around the onsen', 'Construir um futuro local ao redor do onsen'],
  '温泉': ['Onsen', 'Onsen'],
  '1階の温泉を再開し、地域の居場所を取り戻す。': ['Reopen the first-floor onsen and restore a community gathering place.', 'Reabrir o onsen do primeiro andar e recuperar um ponto de encontro comunitário.'],
  '学びと挑戦': ['Learning and experimentation', 'Aprendizado e experimentação'],
  '上階を学生、研究者、地域企業の活動拠点へ。': ['Turn the upper floors into a base for students, researchers, and local companies.', 'Transformar os andares superiores em uma base para estudantes, pesquisadores e empresas locais.'],
  '周辺の土地に、福井で使う計算力をつくる。': ['Build computing power for Fukui on the surrounding land.', 'Criar capacidade computacional para Fukui nos terrenos ao redor.'],
  '食と起業': ['Food and entrepreneurship', 'Alimentação e empreendedorismo'],
  '小さな店や台所から、地域の商いを始める。': ['Give local people a low-cost place to start small food businesses.', 'Dar às pessoas locais um lugar acessível para iniciar pequenos negócios de alimentação.'],
  '祭りと文化': ['Festivals and culture', 'Festivais e cultura'],
  'イベントと光で、夜も人が集まる場所へ。': ['Use festivals and light to bring people together after dark.', 'Usar festivais e luz para reunir pessoas depois do anoitecer.'],
  '温泉 — 地域の目的地となる大露天風呂': ['Onsen — A Large Rotenburo Designed as a Regional Destination', 'Onsen — Um grande rotenburo concebido como destino regional'],
  '1階の温泉を地域の集いの場として再開し、AIの田んぼ（データセンター）の回収熱で温泉水を補助加温できるかを技術検証します。': ['Reopen the first-floor onsen as a community gathering place and test whether recovered heat from the AI Rice Field data center can supplement its water heating.', 'Reabrir o onsen do primeiro andar como ponto de encontro comunitário e testar se o calor recuperado do data center AI Rice Field pode complementar o aquecimento da água.'],
  '学ぶ・試す・立ち上げる': ['Learning, Experimentation, and Launch', 'Aprendizagem, experimentação e lançamento'],
  '上階を、学生・研究者がAIを学び、試し、福井発の解決策を立ち上げる拠点へ。': ['Turn the upper floors into a base where students and researchers learn and test AI—and launch solutions built in Fukui.', 'Transformar os andares superiores em uma base onde estudantes e pesquisadores aprendem e testam IA — e lançam soluções criadas em Fukui.'],
  'AIの「田んぼ」— 地域の計算力': ['AI “Rice Field” — Local Compute', '“Arrozal” de IA — Computação local'],
  '既存の温泉棟とは別に、周辺の土地へ福井で使う計算力をつくる。': ['Build computing power for Fukui on the surrounding land, separate from the existing onsen building.', 'Criar capacidade computacional para Fukui nos terrenos ao redor, separada do edifício existente do onsen.'],
  '小さな店や台所から、低い初期負担で地域の食の商いを始められる場所へ。': ['Give local people a low-cost place to start small food businesses.', 'Dar às pessoas locais um lugar de baixo custo para iniciar pequenos negócios de alimentação.'],
  'D-Kの光・祭り・文化': ['D-K Light, Festivals, and Culture', 'Luz D-K, festivais e cultura'],
  '長谷川章氏のD-Kによる夜の光の体験と地域イベントで、福井内外から人が集まる場所へ。': ['A proposed nightly Akira Hasegawa D-K light experience and community events can draw people from Fukui and beyond.', 'Uma experiência noturna proposta de luz D-K de Akira Hasegawa e eventos comunitários podem atrair pessoas de Fukui e de outras regiões.'],
  'AIにも、': ['AI needs', 'A IA também precisa de'],
  '「ごはん」': ['“food,” too.', '“alimento”.'],
  'が必要です。': ['', ''],
  '人にお米をつくる田んぼがあるように、AIには「計算する力」を生み出す場所が必要です。それがデータセンターです。': ['Just as rice fields produce food for people, AI needs a place that produces computing power. That place is a data center.', 'Assim como os arrozais produzem alimento para as pessoas, a IA precisa de um lugar que produza capacidade computacional. Esse lugar é um data center.'],
  '電力・データ・': ['Electricity, data, and', 'Energia, dados e'],
  'コンピューター': ['computers', 'computadores'],
  'データセンター': ['Data center', 'Data center'],
  '計算する力': ['Computing power', 'Capacidade computacional'],
  'コンピュート': ['Compute', 'Computação'],
  'AIが仕事をする': ['AI gets to work', 'A IA começa a trabalhar'],
  'この施設が農機を直接動かすわけではありません。地域で使える計算力が、農業AI、教育、研究、ものづくりの開発と利用を支えます。': ['This facility would not directly operate farm machinery. It would provide local computing power for developing and using AI in agriculture, education, research, and manufacturing.', 'Esta instalação não operaria diretamente máquinas agrícolas. Ela forneceria capacidade computacional local para desenvolver e usar IA na agricultura, educação, pesquisa e indústria.'],
  '福井の電力 → 福井の計算力 → 福井の知恵 → 福井の仕事': ['Fukui energy → Fukui compute → Fukui knowledge → Fukui jobs', 'Energia de Fukui → computação de Fukui → conhecimento de Fukui → empregos em Fukui'],
  '農業': ['Agriculture', 'Agricultura'],
  'ドローン、畑の見守り、雑草検知、収穫予測などの研究へ。': ['Research for drones, field monitoring, weed detection, and yield forecasting.', 'Pesquisa para drones, monitoramento de lavouras, detecção de ervas daninhas e previsão de produtividade.'],
  '教育・大学': ['Education and universities', 'Educação e universidades'],
  '学生と研究者が、地域でAIを学び試せる環境へ。': ['Give students and researchers a local place to learn and test AI.', 'Dar a estudantes e pesquisadores um lugar local para aprender e testar IA.'],
  '地域企業': ['Local companies', 'Empresas locais'],
  '製造、設計、業務改善に使うAIを福井で育てる。': ['Develop AI in Fukui for manufacturing, design, and better operations.', 'Desenvolver IA em Fukui para indústria, projeto e melhoria das operações.'],
  '現在から二つの選択肢への流れ': ['From today to two possible futures', 'De hoje a dois futuros possíveis'],
  '再生後の五つの役割': ['Five parts of the renewed site', 'Cinco partes do local renovado'],
  'AIの田んぼが計算力を生み出す流れ': ['How an AI Rice Field produces computing power', 'Como um arrozal de IA produz capacidade computacional'],
  '福井での活用例': ['Examples for Fukui', 'Exemplos para Fukui'],
  '46.8億円': ['¥4.68B', '¥4,68 bi'],
  '約68億円': ['About ¥6.8B', 'Cerca de ¥6,8 bi'],
  '約15.8億円': ['About ¥1.58B', 'Cerca de ¥1,58 bi'],
  '129,649人': ['129,649 people', '129.649 pessoas'],
  '🍜 地域の食・横丁': ['🍜 Local food and yokocho', '🍜 Comida local e yokocho'],
  '🎨 D-K・祭り・夜間滞在': ['🎨 D-K, festivals, and evening visits', '🎨 D-K, festivais e visitas noturnas'],
  '♨️ 温泉・宿泊': ['♨️ Onsen and overnight stays', '♨️ Onsen e hospedagem'],
  '✈️ 空港・新幹線からの周遊': ['✈️ Connections from the airport and Shinkansen', '✈️ Conexões a partir do aeroporto e do Shinkansen'],
  '次回の公開ミーティング': ['Next public meeting', 'Próxima reunião pública'],
  'メンバー予定': ['Member calendar', 'Calendário de membros'],
  'LINEコミュニティ参加者向け': ['For LINE community participants', 'Para participantes da comunidade LINE'],
  '公開できる情報が確定してから掲載します。先に案内を受け取りたい方は、LINEコミュニティにご参加ください。': ['We will publish details only after the date and location are confirmed. Join the LINE community to receive the announcement first.', 'Publicaremos os detalhes somente após a confirmação da data e do local. Entre na comunidade LINE para receber o anúncio primeiro.'],
  'LINEで案内を受け取る': ['Get updates on LINE', 'Receber atualizações no LINE'],
  '地域での小さな対話、準備会、情報共有の詳しい予定を、参加メンバーへLINEでお知らせする構想です。': ['The plan is to share detailed schedules for local conversations, preparation meetings, and project updates with participating members through LINE.', 'O plano é compartilhar pelo LINE os horários de conversas locais, reuniões de preparação e atualizações do projeto com os membros participantes.'],
  '現在、このウェブサイトに会員認証や保護されたカレンダーはありません。ボタンが専用ページを開くようには見せません。': ['This website does not yet have member authentication or a protected calendar. We will not pretend that it does.', 'Este site ainda não possui autenticação de membros nem calendário protegido. Não fingiremos que possui.'],
  'ウェブサイトだけで決めるプロジェクトではありません。周辺地域を歩き、住民の経験、心配、希望を聞くことから始めます。': ['This project will not be decided by a website alone. It begins by walking through nearby communities and listening to residents’ experiences, concerns, and hopes.', 'Este projeto não será decidido apenas por um site. Ele começa caminhando pelas comunidades próximas e ouvindo experiências, preocupações e esperanças dos moradores.'],
  '閉館した施設を、そのまま残す話ではありません。温泉を中心に、人が集まり、学び、働き、挑戦できる場所へ育てる提案です。': ['The proposal is not to freeze a closed facility in time. It is to grow a place around the onsen where people gather, learn, work, and try new things.', 'A proposta não é congelar no tempo uma instalação fechada. É criar ao redor do onsen um lugar onde pessoas se reúnam, aprendam, trabalhem e experimentem coisas novas.'],
  '012提供の配置構想です。完成済みの施設を示す画像ではありません。': ['A site concept supplied by 012. It does not show a completed facility.', 'Um conceito de implantação fornecido por 012. Não mostra uma instalação concluída.'],
  '既存建物、駐車場、周辺土地を使ったプロジェクト配置構想': ['Project site concept using the existing building, parking, and surrounding land', 'Conceito do projeto usando o edifício existente, estacionamento e terrenos ao redor'],
  '温泉と地域の食がつながる将来イメージです。実際の配置・規模・熱利用は調査で決まります。': ['A future concept connecting the onsen with local food. Final layout, scale, and heat use depend on further study.', 'Um conceito futuro que conecta o onsen à comida local. O layout, a escala e o uso do calor dependem de estudos adicionais.'],
  '露天風呂と小さな飲食店が夜に集まる将来構想': ['Future concept with rotenburo and small food businesses active into the evening', 'Conceito futuro com rotenburo e pequenos negócios de alimentação ativos à noite'],
  'D-K（デジタル掛け軸）を提唱する長谷川章氏': ['Akira Hasegawa, creator of D-K (Digital Kakejiku)', 'Akira Hasegawa, criador do D-K (Digital Kakejiku)'],
  'お米と人の関係は、コンピュートとAIの関係に似ています': ['Rice is to people as compute is to AI', 'O arroz está para as pessoas assim como a computação está para a IA'],
  '福井市と市民': ['Fukui City and its residents', 'Cidade de Fukui e seus moradores'],
  '解体か再生かを、公開された根拠と地域の声で判断する。': ['Compare demolition and reuse using public evidence and community voices.', 'Comparar demolição e reutilização com evidências públicas e vozes da comunidade.'],
  '天菅生町と近隣住民': ['Amasugō and nearby residents', 'Amasugō e moradores próximos'],
  '騒音・水・交通・景観・温泉再開について、最初に話を聞く人たち。': ['The first people to consult about noise, water, traffic, landscape, and reopening the onsen.', 'As primeiras pessoas a consultar sobre ruído, água, trânsito, paisagem e reabertura do onsen.'],
  '子ども・学生・研究者': ['Children, students, and researchers', 'Crianças, estudantes e pesquisadores'],
  '大安寺の学びと、まず県内5大学の研究・教育に地域の計算資源をつなぐ。': ['Connect local compute first to learning in Daianji and research and education at five prefectural universities.', 'Conectar primeiro a computação local ao aprendizado em Daianji e à pesquisa e educação em cinco universidades da província.'],
  '農業AI、ドローン、自動運転農機、ものづくりDXを地域で育てる。': ['Develop agricultural AI, drones, autonomous farm machinery, and manufacturing DX in the region.', 'Desenvolver na região IA agrícola, drones, máquinas agrícolas autônomas e transformação digital da indústria.'],
  '技術・運営パートナー': ['Technical and operating partners', 'Parceiros técnicos e operacionais'],
  '電力、通信、冷却、建築、セキュリティ、データセンター運営の実務家。': ['Practitioners in power, communications, cooling, construction, security, and data-center operations.', 'Profissionais de energia, comunicações, resfriamento, construção, segurança e operação de data centers.'],
  '公共資産、地域AI基盤、農業・教育・産業の未来を守る': ['Protect a public asset and the future of local AI, agriculture, education, and industry', 'Proteger um patrimônio público e o futuro da IA local, agricultura, educação e indústria'],
  '温泉を守れ、すかっとランド九頭竜の解体を止めよう': ['Save the onsen and stop the demolition of Sukatto Land Kuzuryu', 'Salvar o onsen e impedir a demolição do Sukatto Land Kuzuryu'],
  '福井県福井市天菅生町3-10': ['3-10 Amasugōchō, Fukui City, Fukui Prefecture', '3-10 Amasugōchō, Cidade de Fukui, Província de Fukui'],
  '会って、': ['Meet.', 'Encontrar.'],
  '話す。': ['Listen.', 'Escutar.'],
  '日程・場所を確認中': ['Date and location being confirmed', 'Data e local em confirmação'],
  'いまは、': ['For now,', 'Por enquanto,'],
  '二人から。': ['we begin with two.', 'começamos com dois.'],
  '福井に、': ['What will', 'O que ficará'],
  '何が残る？': ['Fukui gain?', 'para Fukui?'],
  '8つの地域価値を見る': ['See eight community benefits', 'Veja oito benefícios para a comunidade'],
  '計算機だけではない。': ['It is about more than computers.', 'É mais do que computadores.'],
  '地域に残る価値': ['It is value that stays local.', 'É valor que permanece na região.'],
  '資料・根拠を見る': ['View sources and documents', 'Ver fontes e documentos'],
  '物語': ['Story', 'História'],
  'AIの田んぼ': ['AI Rice Field', 'Arrozal de IA'],
  'チーム': ['Team', 'Equipe'],
  '名前を加える': ['Add your name', 'Adicione seu nome'],
  'LINEに参加': ['Join on LINE', 'Entre no LINE'],
  'LINEで参加 ↗': ['Join on LINE ↗', 'Entre no LINE ↗'],
  'LINEでチームに参加': ['Join the team on LINE', 'Entre na equipe pelo LINE'],
  '市との最初の対話は完了 / 資金募集ではありません': ['Initial dialogue with the city completed / This is not fundraising', 'Diálogo inicial com a cidade concluído / Isto não é captação de recursos'],
  '緊急告知｜8月31日（月）午前10時、市との会合。Monk UnDaoDuが「SAVE OUR ONSEN」を配布します。一緒に参加しよう。詳細はLINEへ。': ['URGENT NOTICE | Monday, August 31, 10:00 AM — Meeting with the City. Monk UnDaoDu will be there handing out SAVE OUR ONSEN. Join him. Details on LINE.', 'AVISO URGENTE | Segunda-feira, 31 de agosto, 10h — Reunião com a Cidade. Monk UnDaoDu estará distribuindo SAVE OUR ONSEN. Junte-se a ele. Detalhes no LINE.'],
  '工事が始まる前に、': ['Before construction begins,', 'Antes que a obra comece,'],
  '未来の選択肢を': ['make the future option', 'transformar a opção de futuro'],
  '形にする。': ['real.', 'em realidade.'],
  '市との最初の対話は終わりました。次は市議会に、解体契約などが不可逆になる時点まで再生提案の資格を残す正式措置を求めます。市の責任を新しい運営主体へ移し、土地所有者と合意し、解体より市の総負担を減らせる案を期限前に示します。': ['The initial dialogue with the city is complete. We now ask the City Council for a formal measure that keeps a qualified reuse proposal eligible until a demolition contract or another irreversible commitment is made. Before that deadline, we will present a plan that transfers city liability to a new operator, reaches agreement with landowners, and costs the city less than demolition.', 'O diálogo inicial com a cidade foi concluído. Agora pedimos ao Conselho Municipal uma medida formal que mantenha uma proposta qualificada de reutilização elegível até a contratação da demolição ou outro compromisso irreversível. Antes desse prazo, apresentaremos um plano que transfira a responsabilidade da cidade para um novo operador, obtenha acordo com os proprietários e custe menos à cidade do que a demolição.'],
  '温泉を守るチームに名前を加える': ['Add your name to save the onsen', 'Adicione seu nome para salvar o onsen'],
  '物語を読む': ['Read the story', 'Leia a história'],
  'この建物を、地域の未来に残す価値はありますか？': ['Is this building worth preserving for the community’s future?', 'Vale a pena preservar este edifício para o futuro da comunidade?'],
  'これは、古い建物の話ではない。': ['Demolition is madness.', 'Esta não é uma história sobre um prédio antigo.'],
  '福井の次の30年を動かす計算力を、': ['Fukui would pay to erase an asset—', 'É sobre quem controla a computação '],
  '誰が持つかという話です。': ['and 30 years of possibility.', 'que impulsionará os próximos 30 anos de Fukui.'],
  '年間13万人の実績は、': ['A proven audience of 130,000 a year', 'Um público comprovado de 130 mil pessoas por ano'],
  '地域経済の出発点。': ['is a starting point for the local economy.', 'é um ponto de partida para a economia local.'],
  '温泉に、地域の食、D-K、祭り、学びを重ねれば、滞在時間と地域での消費を増やせる可能性があります。': ['Adding local food, D-K, festivals, and learning to the onsen could encourage longer stays and more local spending.', 'Somar comida local, D-K, festivais e aprendizagem ao onsen pode estimular estadias mais longas e mais gastos na região.'],
  '年間129,649人。': ['129,649 annual visits.', '129.649 visitas anuais.'],
  '需要は、すでにあった。': ['The demand was already there.', 'A demanda já existia.'],
  '次の価値は、一回の来場を地域での食事、買い物、宿泊、交通にどれだけつなげられるかで決まります。': ['What comes next depends on how each visit connects to local food, shopping, lodging, and transport.', 'O próximo valor depende de quanto cada visita se conecta à alimentação, às compras, à hospedagem e ao transporte locais.'],
  '約1.3億〜7.2億円 / 年': ['About ¥130M–¥720M / year', 'Cerca de ¥130–720 milhões / ano'],
  '直接消費シナリオ': ['Direct-spending scenario', 'Cenário de gasto direto'],
  '来場者の直接消費シナリオ': ['Direct-spending scenario', 'Cenário de gasto direto dos visitantes'],
  '約38.9億〜215.7億円 / 30年': ['About ¥3.9B–¥21.6B / 30 years', 'Cerca de ¥3,9–21,6 bilhões / 30 anos'],
  '30年間の直接消費機会': ['30-year direct-spending opportunity', 'Oportunidade de gasto direto em 30 anos'],
  '地域の食・横丁': ['Local food and yokocho', 'Comida local e yokocho'],
  'D-K・祭り・夜間滞在': ['D-K, festivals, and evening visits', 'D-K, festivais e visitas noturnas'],
  '温泉・宿泊': ['Onsen and overnight stays', 'Onsen e hospedagem'],
  '空港・新幹線からの周遊': ['Connections from the airport and Shinkansen', 'Conexões a partir do aeroporto e do Shinkansen'],
  '2018年度の利用実績に、1人あたり1,000円の追加消費仮定から、福井県の2025年日帰り観光消費単価5,546円までを掛けた単純な試算です。30年間の数字は、来場者数と単価を一定として割引を行わない説明用の累計です。建設、運営、コンピュート収入、雇用、経済波及効果は含みません。': ['A simple screening calculation applying ¥1,000 in assumed incremental spending through Fukui Prefecture’s 2025 average day-trip spending of ¥5,546 to fiscal-2018 attendance. The 30-year figure holds attendance and spending constant and is not discounted. It excludes construction, operations, compute revenue, jobs, and multiplier effects.', 'Um cálculo preliminar que aplica de ¥1.000 em gasto adicional presumido até a média de ¥5.546 por viagem de um dia em Fukui em 2025 ao público do ano fiscal de 2018. O total de 30 anos mantém público e gasto constantes e não é descontado. Não inclui construção, operação, receita de computação, empregos nem efeitos multiplicadores.'],
  '福井県観光客入込数（推計）2025年': ['Fukui Prefecture Tourism Statistics 2025', 'Estatísticas de Turismo de Fukui 2025'],
  '経済効果を検証する三つの段階': ['Three stages for validating economic impact', 'Três etapas para validar o impacto econômico'],
  '来場者の直接消費': ['Direct visitor spending', 'Gasto direto dos visitantes'],
  '現在数字で示しているのは、この層だけです。': ['This is the only layer currently quantified.', 'Esta é a única camada atualmente quantificada.'],
  '県内取引と所得への波及': ['Local supplier and income effects', 'Efeitos sobre fornecedores e renda locais'],
  '消費項目と県内調達率を確認し、福井県産業連関表で分析します。': ['After confirming spending categories and local capture, analyze them with Fukui’s input-output table.', 'Após confirmar as categorias de gasto e a retenção local, analisá-las com a matriz insumo-produto de Fukui.'],
  '雇用・税収・地域への還元': ['Jobs, tax revenue, and community returns', 'Empregos, receita tributária e retorno à comunidade'],
  '分析が完了するまで、数字を掲載しません。': ['No figures will be published until that analysis is complete.', 'Nenhum valor será publicado até que essa análise esteja concluída.'],
  '30年間の参考累計と計算方法': ['See the illustrative 30-year total and method', 'Ver o total ilustrativo de 30 anos e o método'],
  '来場者数と消費額が一定の場合の単純累計': ['Simple cumulative total if attendance and spending remain constant', 'Total cumulativo simples se o público e os gastos permanecerem constantes'],
  '割引を行わない説明用の参考値であり、予測ではありません。': ['An undiscounted illustration—not a forecast.', 'Uma ilustração sem desconto — não uma previsão.'],
  '地域キャンペーンは何を測っているか': ['What community campaigns measure', 'O que campanhas comunitárias medem'],
  '福井の予測ではなく、成果指標を設計するための実例です。': ['Examples for designing outcome measures—not forecasts for Fukui.', 'Exemplos para definir indicadores de resultados — não previsões para Fukui.'],
  '新規雇用・設備投資・新規給与を追跡': ['Tracks new jobs, capital investment, and new payroll', 'Acompanha novos empregos, investimento de capital e nova folha de pagamento'],
  '雇用・設備投資・小売売上・世帯所得を追跡': ['Tracks jobs, capital investment, retail sales, and household income', 'Acompanha empregos, investimento de capital, vendas no varejo e renda familiar'],
  'これらの成果や比率を福井に当てはめるものではありません。': ['These outcomes and ratios are not transferred to Fukui.', 'Esses resultados e proporções não são transferidos para Fukui.'],
  '2018年度の利用実績に、1人あたり1,000円の追加消費仮定から、福井県の2025年日帰り観光消費単価5,546円までを掛けた単純な試算です。この試算に含むのは来場者の直接消費だけです。取引先への波及、所得、雇用、税収は、福井県産業連関表による分析が完了するまで含めません。': ['This simple screen applies a ¥1,000 project assumption through Fukui’s 2025 average day-trip spend of ¥5,546 to FY2018 attendance. It includes direct visitor spending only. Supplier effects, income, jobs, and tax revenue remain excluded until a Fukui input-output analysis is complete.', 'Esta estimativa simples aplica uma hipótese do projeto de ¥1.000 até o gasto médio de ¥5.546 por excursionista em Fukui em 2025 ao público do ano fiscal de 2018. Inclui apenas o gasto direto dos visitantes. Efeitos sobre fornecedores, renda, empregos e receita tributária permanecem excluídos até a conclusão de uma análise insumo-produto de Fukui.'],
  '福井県 経済波及効果分析': ['Fukui Prefecture economic-impact analysis', 'Análise de impacto econômico da Província de Fukui'],
  '1994年、市民の健康・交流・憩いのために開館。天然温泉、体育館、宴会場、宿泊・研修機能を備え、2018年度には約13万人が利用しました。公の施設としての機能は2021年6月に廃止されました。': ['Sukatto Land cost ¥4.68 billion to build. Its indexed construction-cost reference is about ¥6.8 billion. Demolition has been discussed at roughly ¥1.58 billion. In fiscal 2018, 129,649 people used it. Before paying to erase that asset, test what it could produce over the next 30 years.', 'Inaugurado em 1994 para saúde, convivência e lazer públicos, o complexo inclui fonte termal natural, ginásio, salões, hospedagem e espaços de treinamento. Cerca de 130 mil pessoas o utilizaram no ano fiscal de 2018. Sua função pública terminou em junho de 2021.'],
  '開館': ['Opened', 'Inauguração'],
  '高齢者を中心とした健康・交流の公共拠点として誕生。': ['Created as a public center for health and connection, especially for older residents.', 'Criado como centro público de saúde e convivência, especialmente para moradores idosos.'],
  '延床面積': ['Total floor area', 'Área construída'],
  '宿泊・研修、健康、交流の複数棟からなる大規模資産。': ['A substantial multi-building asset for lodging, training, health, and community use.', 'Um amplo patrimônio com vários edifícios para hospedagem, treinamento, saúde e convivência.'],
  '2018年度利用': ['Fiscal 2018 use', 'Uso no ano fiscal de 2018'],
  '入館者と宿泊者を合わせた、閉館前の利用実績。': ['Visitors and overnight guests before closure.', 'Visitantes e hóspedes antes do fechamento.'],
  '機能廃止': ['Public use ended', 'Fim da função pública'],
  'いま問われているのは、解体前に再利用を検証するかどうか。': ['The question now is whether reuse will be tested before demolition.', 'A questão agora é se a reutilização será testada antes da demolição.'],
  '捨てる費用と、': ['Compare the cost of disposal', 'Compare o custo de descartar'],
  '残す価値を比べる。': ['with the value of preservation.', 'com o valor de preservar.'],
  '46.8億円は「468億円」ではなく、': ['¥4.68 billion is not ¥46.8 billion.', '¥4,68 bilhões não são ¥46,8 bilhões.'],
  'です。国の建設工事費指数で1994年度から2025年度へ換算すると、同規模の非住宅建築のコスト感は概ね': ['Using Japan’s construction cost index to adjust from fiscal 1994 to fiscal 2025 gives an indicative cost for a comparable non-residential building of approximately', 'O ajuste do ano fiscal de 1994 para 2025 pelo índice japonês de custos de construção indica um custo aproximado para um edifício não residencial comparável de'],
  'です。': ['.', '.'],
  '。これは鑑定額ではなく、公共資産の規模を理解するための参考値です。': ['This is not an appraisal; it is a reference point for understanding the scale of the public asset.', 'Isto não é uma avaliação formal; é uma referência para compreender a escala do patrimônio público.'],
  '福井市の施設資料を見る': ['View Fukui City facility documents', 'Ver documentos da cidade de Fukui'],
  '建設時': ['Original construction', 'Construção original'],
  '福井市の公表資料に記載された建設費。': ['Construction cost stated in Fukui City documents.', 'Custo de construção informado nos documentos da cidade de Fukui.'],
  '指数換算参考': ['Indexed construction-cost reference', 'Referência de custo de construção indexado'],
  '国の建設工事費指数による参考値。鑑定額ではありません。': ['Calculated from Japan’s construction-cost index. This is not an appraisal.', 'Calculado com o índice japonês de custos de construção. Não é uma avaliação formal.'],
  '解体見込み': ['Estimated demolition', 'Demolição estimada'],
  '2026年6月の福井市議会質問資料に示された見込み。': ['Estimate shown in June 2026 Fukui City Council materials.', 'Estimativa apresentada nos documentos do Conselho Municipal de Fukui de junho de 2026.'],
  '現在価値の目安': ['Indexed present value', 'Valor atual indexado'],
  '国交省建設工事費デフレーターを用いた概算。': ['Indicative estimate using the national construction cost deflator.', 'Estimativa indicativa com o deflator nacional de custos de construção.'],
  '市の移行支援枠': ['City transition support', 'Apoio municipal à transição'],
  '未': ['Not', 'Não'],
  '確定': ['confirmed', 'confirmado'],
  '固定10億円ではなく、純回避費用と検証済み資金不足額の小さい方を上限にする提案。': ['The proposal is not a fixed ¥1 billion. Its ceiling would be the lower of the city’s verified avoided net cost and the verified funding gap.', 'A proposta não fixa ¥1 bilhão. O limite seria o menor valor entre o custo líquido evitado pela cidade e a lacuna de financiamento comprovada.'],
  '解体準備は進めても、': ['Demolition preparation may continue,', 'A preparação da demolição pode continuar,'],
  '代案の扉は閉じない': ['but keep the alternative open.', 'mas a alternativa deve permanecer aberta.'],
  '求めるのは、固定60日間の停止ではありません。補正予算、附帯決議、または同等の正式措置により、解体契約の締結など後戻りが困難になる時点まで、条件を満たす再生案を受け付け、解体執行前に比較評価できる道を残すことです。': ['We are not asking for a fixed 60-day pause. We ask for a supplemental budget condition, accompanying resolution, or equivalent formal measure that keeps the door open for a qualified reuse proposal until a demolition contract or another hard-to-reverse commitment, allowing comparison before demolition is executed.', 'Não pedimos uma pausa fixa de 60 dias. Pedimos uma condição no orçamento suplementar, uma resolução anexa ou medida formal equivalente que mantenha aberta a possibilidade de uma proposta qualificada de reutilização até a contratação da demolição ou outro compromisso difícil de reverter, permitindo a comparação antes da execução.'],
  '期限前に、安全性、実行主体、借地合意、資金計画、市の財政効果を証明できた場合、解体案と同じ条件で正式に審査する。': ['If safety, an operating entity, land agreements, financing, and fiscal benefit to the city are proven before the deadline, the reuse plan receives formal review on equal terms with demolition.', 'Se segurança, entidade operadora, acordos fundiários, financiamento e benefício fiscal para a cidade forem comprovados antes do prazo, o plano de reutilização será analisado formalmente em igualdade com a demolição.'],
  '期限': ['Deadline', 'Prazo'],
  '解体契約締結など、公費上の後戻りが困難になる前': ['Before a demolition contract or another fiscally irreversible commitment', 'Antes de um contrato de demolição ou outro compromisso fiscal irreversível'],
  '責任移管': ['Liability transfer', 'Transferência de responsabilidade'],
  '改修・運営・維持・将来処分を適法な範囲で新主体へ': ['Transfer renovation, operation, maintenance, and future disposal to a new entity where lawful', 'Transferir reforma, operação, manutenção e futura destinação a uma nova entidade dentro da lei'],
  '土地合意': ['Land agreement', 'Acordo fundiário'],
  '全敷地の土地所有者と借地条件・負担について合意': ['Agree lease terms and obligations with all landowners', 'Acordar termos de arrendamento e obrigações com todos os proprietários'],
  '解体費を、': ['Turn demolition spending', 'Transformar o gasto com demolição'],
  '地域の再生資本': ['into community renewal capital.', 'em capital de renovação comunitária.'],
  '民間・地域主体が、市から建物の改修、運営、維持管理、借地料、将来の処分責任を引き受ける。土地所有者との合意を整え、解体より市の生涯負担を小さくできるなら、市が回避できる純支出の一部を一回限りの移行支援として活用する。それが提案の核心です。': ['A private or community operator would assume renovation, operation, maintenance, land rent, and future disposal responsibility from the city. If landowner agreements are secured and the city’s lifetime cost is lower than demolition, part of the city’s avoided net expenditure could become one-time transition support. That is the proposal’s core.', 'Um operador privado ou comunitário assumiria da cidade a reforma, operação, manutenção, aluguel do terreno e responsabilidade pela destinação futura. Se houver acordo com os proprietários e o custo total para a cidade for menor que a demolição, parte da despesa líquida evitada poderá se tornar apoio único de transição. Esse é o núcleo da proposta.'],
  '市が回避できる純負担': ['City’s avoided net cost', 'Custo líquido evitado pela cidade'],
  '補助金・民間資金控除後の不足額': ['Verified gap after grants and private capital', 'Lacuna comprovada após subsídios e capital privado'],
  '二つのうち小さい額を上限に、補助、負担金、融資、現物支援など適法で最も市に有利な形を議会・法務・財政審査で決める。': ['The lower figure becomes the ceiling. Council, legal, and fiscal review would select the lawful form most favorable to the city—grant, contribution, loan, or in-kind support.', 'O menor valor será o limite. A análise legislativa, jurídica e fiscal escolherá a forma legal mais favorável à cidade — subsídio, contribuição, empréstimo ou apoio em espécie.'],
  '市の純負担を計算': ['Calculate the city’s net cost', 'Calcular o custo líquido da cidade'],
  '解体、原状回復、契約解除、借地、維持管理から、国・県補助や既支出を調整する。': ['Adjust demolition, restoration, termination, lease, and maintenance costs for national and prefectural grants and prior spending.', 'Ajustar custos de demolição, restauração, rescisão, arrendamento e manutenção por subsídios nacionais e provinciais e gastos anteriores.'],
  '新主体が責任を引き受ける': ['A new entity assumes responsibility', 'Uma nova entidade assume a responsabilidade'],
  '土地所有者と合意する': ['Reach agreement with landowners', 'Chegar a acordo com os proprietários'],
  '公費は最後の不足分へ': ['Public funds cover only the final gap', 'Recursos públicos cobrem apenas a lacuna final'],
  '重要：': ['Important:', 'Importante:'],
  '「10億円」は現時点の確定要求額ではありません。市の純回避額、補助制度、契約状況、民間資金、改修見積を確認して初めて上限が決まります。': ['¥1 billion is not a confirmed request. A ceiling can be set only after verifying the city’s avoided net cost, grant programs, contracts, private capital, and renovation estimates.', '¥1 bilhão não é um pedido confirmado. O limite só poderá ser definido após verificar o custo líquido evitado pela cidade, subsídios, contratos, capital privado e estimativas de reforma.'],
  '地域の計算力が、': ['Local computing power drives', 'A capacidade computacional local move'],
  '地域の知恵': ['local intelligence.', 'a inteligência local.'],
  'を動かす。': ['', ''],
  'AIは魔法ではありません。学習・推論を行う計算資源が必要です。地域で使える計算力があれば、農業、教育、製造、医療、防災のデータを地域の課題解決へつなげられます。': ['AI is not magic. It requires computing resources for training and inference. Locally available compute can connect agricultural, educational, manufacturing, health, and disaster-prevention data to local problem solving.', 'IA não é mágica. Ela exige recursos computacionais para treinamento e inferência. Computação disponível localmente pode conectar dados de agricultura, educação, indústria, saúde e prevenção de desastres à solução de problemas locais.'],
  '電力': ['Power', 'Energia'],
  '地域の脱炭素電源': ['Local low-carbon power', 'Energia local de baixo carbono'],
  '計算': ['Compute', 'Computação'],
  '大学・企業・農業AI': ['Universities, business, agricultural AI', 'Universidades, empresas e IA agrícola'],
  '排熱': ['Waste heat', 'Calor residual'],
  '温泉・暖房・温室へ': ['For onsen, heating, and greenhouses', 'Para onsen, aquecimento e estufas'],
  '還元': ['Return', 'Retorno'],
  '仕事・学び・地域便益': ['Jobs, learning, community benefit', 'Empregos, aprendizado e benefício comunitário'],
  '液冷・排熱利用・受電方法は、現地調査と専門事業者の設計で初めて確定します。ウェブサイトは可能性を示し、断定はしません。': ['Liquid cooling, heat reuse, and power supply can be confirmed only through site investigation and specialist design. This website presents possibilities, not guarantees.', 'Resfriamento líquido, reaproveitamento de calor e fornecimento elétrico só poderão ser confirmados após investigação do local e projeto especializado. Este site apresenta possibilidades, não garantias.'],
  '日本のための巨大データセンターではない。': ['Not a giant data center for Japan.', 'Não um megadata center para o Japão.'],
  '福井のためのAI田んぼ': ['An AI rice field for Fukui.', 'Um arrozal de IA para Fukui.'],
  '米を育てる田んぼが地域の命を支えるように、地域で管理できる計算力が、次の教育と産業を育てます。福井の子ども、学生、研究者、農家、企業が、海外や大都市の価格に左右されず、低価格で自分たちのAIを動かせる基盤をつくります。': ['As rice fields sustain community life, locally managed computing power can grow the next generation of education and industry. The goal is affordable infrastructure that lets Fukui’s children, students, researchers, farmers, and businesses run their own AI without being controlled by overseas or major-city pricing.', 'Assim como os arrozais sustentam a vida comunitária, a computação gerida localmente pode cultivar a próxima geração de educação e indústria. O objetivo é uma infraestrutura acessível para que crianças, estudantes, pesquisadores, agricultores e empresas de Fukui executem sua própria IA sem depender dos preços de mercados externos ou grandes cidades.'],
  '地域のコンピュートは、地域の未来を育てる土です。': ['Community compute is the soil that grows the community’s future.', 'A computação comunitária é o solo que cultiva o futuro da comunidade.'],
  'まず福井・永平寺・越前を中心とする5大学との利用協議を目標にし、県内全6大学、短大、高専、学校教育へ拡張する構想です。参加校・配分は未合意で、今後の協議事項です。': ['The initial goal is to discuss use with five universities centered around Fukui, Eiheiji, and Echizen, then expand to all six prefectural universities, junior colleges, technical colleges, and schools. Participation and allocation are not agreed and remain future discussion items.', 'A meta inicial é discutir o uso com cinco universidades de Fukui, Eiheiji e Echizen, expandindo depois para as seis universidades da província, faculdades, institutos técnicos e escolas. Participação e alocação ainda não foram acordadas.'],
  '1 MWで実証し、': ['Prove it at 1 MW,', 'Comprovar em 1 MW,'],
  '合意と需要に合わせて育てる。': ['then grow with consent and demand.', 'depois crescer conforme o acordo e a demanda.'],
  'Google Driveの1 MW財務モデルを基準にした単純比例の説明用シナリオです。価格、稼働率、GPU世代、受電余力、工事費によって大きく変わるため、投資予測ではありません。': ['This illustrative scenario scales the internal 1 MW financial model proportionally. Prices, utilization, GPU generation, power capacity, and construction costs can change it substantially. It is not an investment forecast.', 'Este cenário ilustrativo amplia proporcionalmente o modelo financeiro interno de 1 MW. Preços, utilização, geração de GPUs, capacidade elétrica e custos de construção podem alterá-lo significativamente. Não é uma previsão de investimento.'],
  '規模': ['Scale', 'Escala'],
  'GPU目安': ['Indicative GPUs', 'GPUs indicativas'],
  '年間電力量上限': ['Annual energy ceiling', 'Limite anual de energia'],
  '年間総収入モデル': ['Annual gross revenue model', 'Modelo de receita bruta anual'],
  '直接雇用目安': ['Indicative direct jobs', 'Empregos diretos indicativos'],
  '教育向け配分案': ['Proposed education allocation', 'Alocação educacional proposta'],
  '温水の設計仮説': ['Warm-water design hypothesis', 'Hipótese de projeto de água quente'],
  '大きさを競う前に、': ['Before competing on size,', 'Antes de competir em tamanho,'],
  '地域との約束': ['design the community compact.', 'desenhar o compromisso comunitário.'],
  'を設計する。': ['', ''],
  '米国ではデータセンターの電力使用が2023年の4.4%から、2028年には6.7–12%へ拡大する可能性があると米エネルギー省が報告しています。日本が同じ集中型モデルを追うだけでは、電力・水・地域負担を後から調整することになります。': ['The U.S. Department of Energy reports that data centers could grow from 4.4% of U.S. electricity use in 2023 to 6.7–12% by 2028. If Japan simply follows the same centralized model, power, water, and community burdens will be addressed only after the fact.', 'O Departamento de Energia dos EUA informa que data centers podem passar de 4,4% do consumo elétrico em 2023 para 6,7–12% em 2028. Se o Japão apenas seguir o mesmo modelo centralizado, os impactos sobre energia, água e comunidades serão tratados somente depois.'],
  '日本の強みは、東京・大阪へすべてを集めることではなく、地方の電源、既存建物、人材、課題を小さな計算拠点で結ぶこと。経産省自身も地域分散と地域共生を重視し、福井市を脱炭素電源活用型GX戦略地域の有望地域に選んでいます。': ['Japan’s strength is not concentrating everything in Tokyo and Osaka. It is connecting regional power, existing buildings, people, and problems through smaller computing hubs. Japan’s economy ministry also emphasizes regional distribution and coexistence and has selected Fukui City as a promising GX strategy area using low-carbon power.', 'A força do Japão não está em concentrar tudo em Tóquio e Osaka, mas em conectar energia regional, edifícios existentes, pessoas e problemas por meio de centros computacionais menores. O ministério da economia também enfatiza distribuição e convivência regional e selecionou Fukui como área promissora de estratégia GX com energia de baixo carbono.'],
  '巨大・集中・外部負担': ['Giant, centralized, externalized costs', 'Gigante, centralizado, custos externalizados'],
  '小さく・分散・地域所有感': ['Small, distributed, locally rooted', 'Pequeno, distribuído e enraizado localmente'],
  '2023年の全国の空き家': ['vacant homes nationwide in 2023', 'moradias vazias no país em 2023'],
  '地域グリーンDCの長期ビジョン': ['Long-term vision for local green data centers', 'Visão de longo prazo para data centers verdes locais'],
  '「データセンターを置けるか」だけでなく、': ['Do not ask only, “Can a data center fit here?” Ask first,', 'Não pergunte apenas “Cabe um data center aqui?”. Pergunte primeiro:'],
  '「この地域が欲しいデータセンターとは何か」': ['“What kind of data center does this community want?”', '“Que tipo de data center esta comunidade deseja?”'],
  'を先に決める。': ['', ''],
  '最初に集めるのは、': ['First gather', 'Primeiro, reunir'],
  'お金ではなく': ['stakeholders—not money.', 'as pessoas envolvidas — não dinheiro.'],
  '当事者': ['', ''],
  '資金の話を始める前に、解体を止め、土地・行政・教育・需要を一つの実行可能な代案につなぎます。': ['Before discussing capital, stop demolition and connect land, government, education, and demand into one workable alternative.', 'Antes de discutir capital, interromper a demolição e conectar terra, governo, educação e demanda em uma alternativa viável.'],
  '温泉を守るための関係者づくりの順序': ['Stakeholder-building sequence to save the onsen', 'Sequência de formação de partes interessadas para salvar o onsen'],
  '解体を止め、比較の時間を確保する': ['Stop Demolition. Keep Time to Compare.', 'Interromper a demolição. Preservar tempo para comparar.'],
  '条件を満たす代案を比較できるまで、後戻りできない解体契約を結ばないよう求める。': ['Ask that no irreversible demolition contract be executed until a qualified alternative can be compared.', 'Pedir que nenhum contrato irreversível de demolição seja executado até que uma alternativa qualificada possa ser comparada.'],
  'COGDC推進チームをつくる': ['Build the COGDC Coalition', 'Formar a coalizão COGDC'],
  '地域住民、発起人、技術・運営の実務家、公益パートナーを一つの実行チームへ。': ['Bring residents, organizers, technical and operating experts, and public-interest partners into one delivery team.', 'Reunir moradores, organizadores, especialistas técnicos e operacionais e parceiros de interesse público em uma equipe de execução.'],
  '地権者と合意する': ['Secure Landowner Agreement', 'Firmar acordo com os proprietários'],
  '地代、責任、期間、将来の選択肢を含む土地利用の条件を、地権者と協議する。': ['Negotiate land-use terms covering rent, responsibility, duration, and future options with the landowners.', 'Negociar com os proprietários os termos de uso da terra, incluindo aluguel, responsabilidades, duração e opções futuras.'],
  '市が審査できる代案にする': ['Present a City-Ready Alternative', 'Apresentar uma alternativa pronta para análise da cidade'],
  '安全性、責任移管、資金計画、市の財政効果を示し、正式に比較できる提案へ。': ['Demonstrate safety, liability transfer, financing, and fiscal impact so the City can formally compare the proposal.', 'Demonstrar segurança, transferência de responsabilidade, financiamento e impacto fiscal para que a cidade possa comparar formalmente a proposta.'],
  '福井の大学と利用計画をつくる': ['Define Use with Fukui Universities', 'Definir o uso com as universidades de Fukui'],
  '教育・研究で必要な計算力と、最初に実行する地域プロジェクトを具体化する。': ['Define the compute needed for education and research and the first regional projects to run.', 'Definir a computação necessária para educação e pesquisa e os primeiros projetos regionais a executar.'],
  '企業顧客・事業パートナーを確保する': ['Secure Corporate Customers and Partners', 'Garantir clientes corporativos e parceiros'],
  '電力、通信、建設、運営の体制と、計算力を利用する中核顧客の約束を積み上げる。': ['Build commitments for power, networks, construction, operations, and anchor customers that will use the compute.', 'Construir compromissos para energia, redes, construção, operação e clientes âncora que utilizarão a computação.'],
  '012と0102を核に、Endorsers、土地所有者、地域の人々、教育・技術の仲間が加わる、生きたチームディレクトリです。写真をタップすると、その人の物語へ進みます。': ['A living directory built around 012 and 0102, joined by endorsers, landowners, community members, educators, and technical collaborators. Tap a photograph to open that person’s story.', 'Um diretório vivo centrado em 012 e 0102, com apoiadores, proprietários, comunidade, educadores e colaboradores técnicos. Toque em uma foto para abrir a história daquela pessoa.'],
  '顔が見える。': ['See the faces.', 'Veja os rostos.'],
  '役割がわかる。': ['Understand the roles.', 'Entenda os papéis.'],
  '人物名と役割は確認できた範囲だけを掲載します。写真は、それだけで支持・提携を意味しません。': ['Only verified names and roles are published. A photograph alone does not imply endorsement or partnership.', 'Somente nomes e funções verificados são publicados. Uma fotografia, por si só, não implica apoio ou parceria.'],
  '関心を、': ['Turn interest', 'Transformar interesse'],
  '実行できる代案に変える。': ['into a workable alternative.', 'em uma alternativa viável.'],
  'イベントで地域の声を可視化する': ['Make community voices visible at the event', 'Tornar visíveis as vozes da comunidade no evento'],
  '議会に正式な条件変更を求める': ['Ask the council for a formal condition change', 'Pedir ao conselho uma mudança formal de condição'],
  '安全性・需要・責任移管を証明する': ['Prove safety, demand, and liability transfer', 'Comprovar segurança, demanda e transferência de responsabilidade'],
  '条件達成で資金の振替審査へ': ['Trigger funding review when conditions are met', 'Acionar a análise de recursos quando as condições forem cumpridas'],
  '温泉を守るチームに、': ['Add', 'Adicione'],
  'あなたの名前': ['your name to the team saving the onsen.', 'seu nome à equipe que salva o onsen.'],
  'を。': ['', ''],
  'これは寄付や投資の申込みではありません。イベントで声を届けたい人、施設を利用したことがある人、教育・農業・技術で協力できる人をつなぎ、代案を実行できるチームへ育てるための登録です。登録名を本人の許可なく公開することはありません。': ['This is not a donation or investment application. It connects people who want to speak at the event, former facility users, and people who can contribute in education, agriculture, or technology. Names will not be published without permission.', 'Isto não é uma solicitação de doação ou investimento. O cadastro conecta pessoas que desejam falar no evento, antigos usuários e colaboradores de educação, agricultura ou tecnologia. Os nomes não serão publicados sem autorização.'],
  '旧すかっとランド九頭竜': ['Former Sukatto Land Kuzuryu', 'Antigo Sukatto Land Kuzuryu'],
  '約1分。必須項目は3つです。': ['About one minute. Three required fields.', 'Cerca de um minuto. Três campos obrigatórios.'],
  'お名前 / ニックネーム': ['Name / nickname', 'Nome / apelido'],
  'メールアドレス': ['Email address', 'Endereço de e-mail'],
  'あなたとの関わり': ['Your connection', 'Sua relação'],
  '必須': ['Required', 'Obrigatório'],
  '選択してください': ['Please select', 'Selecione'],
  '天菅生町・近隣の住民': ['Resident of Amasugō or nearby', 'Morador de Amasugō ou arredores'],
  '施設を利用したことがある': ['Former facility user', 'Antigo usuário do complexo'],
  '福井市・福井県の住民': ['Fukui City / Prefecture resident', 'Morador da cidade / província de Fukui'],
  '学生・教育・研究': ['Student / education / research', 'Estudante / educação / pesquisa'],
  '農業・地域産業': ['Agriculture / local industry', 'Agricultura / indústria local'],
  '技術・データセンター': ['Technology / data centers', 'Tecnologia / data centers'],
  '行政・公共政策': ['Government / public policy', 'Governo / políticas públicas'],
  'その他': ['Other', 'Outro'],
  'この場所の思い出、期待、できること（任意）': ['Memories, hopes, or how you can help (optional)', 'Memórias, expectativas ou como pode ajudar (opcional)'],
  'あなたの言葉で教えてください。': ['Tell us in your own words.', 'Conte com suas próprias palavras.'],
  'プロジェクトの進捗連絡と、匿名化した意見の集計に同意します。': ['I agree to receive project updates and to the anonymous aggregation of my comments.', 'Concordo em receber atualizações do projeto e com a agregação anônima dos meus comentários.'],
  '送信中…': ['Sending…', 'Enviando…'],
  'チームに名前を加える': ['Add my name to the team', 'Adicionar meu nome à equipe'],
  'ありがとうございます。温泉を守るチームにあなたの名前を受け取りました。': ['Thank you. Your name has been added to the team saving the onsen.', 'Obrigado. Seu nome foi adicionado à equipe que está salvando o onsen.'],
  '送信できませんでした。時間を置いて再度お試しいただくか、LINEからご参加ください。': ['Submission failed. Please try again later or join through LINE.', 'Não foi possível enviar. Tente novamente mais tarde ou participe pelo LINE.'],
  '根拠を公開する。': ['Publish the evidence.', 'Publicar as evidências.'],
  '確定事実、外部統計、創設者の未来予測、プロジェクト内部モデル、未検証の仮説を区別しています。': ['We distinguish confirmed facts, external statistics, the founder’s future framework, internal project models, and unverified hypotheses.', 'Distinguimos fatos confirmados, estatísticas externas, a visão de futuro do fundador, modelos internos do projeto e hipóteses não verificadas.'],
  'モデル注記：': ['Model note:', 'Nota do modelo:'],
  '1–4 MWの収入・雇用・GPU数は、Google Drive内の「Project eSingularity – Phase 1 Financial Model」を基準にした説明用の単純比例です。融資、投資、収益を勧誘または保証するものではありません。デューデリジェンス前の数値です。': ['The 1–4 MW revenue, employment, and GPU figures are illustrative proportional extensions of the internal “Project eSingularity – Phase 1 Financial Model.” They do not solicit or guarantee financing, investment, or returns and precede due diligence.', 'Os números de receita, empregos e GPUs de 1–4 MW são extensões proporcionais ilustrativas do “Project eSingularity – Phase 1 Financial Model”. Não solicitam nem garantem financiamento, investimento ou retorno e são anteriores à diligência.'],
  '写真から、': ['From a photograph', 'De uma fotografia'],
  '一人ひとりの物語': ['to each person’s story.', 'à história de cada pessoa.'],
  'へ。': ['', ''],
  'これは完成した組織図ではありません。012と0102を核に、Endorsers、土地所有者、地域の人々、教育者、技術者、世界のネットワークが加わっていく、生きたディレクトリです。': ['This is not a finished organization chart. It is a living directory built around 012 and 0102, growing with endorsers, landowners, community members, educators, technical experts, and global connections.', 'Este não é um organograma concluído. É um diretório vivo centrado em 012 e 0102, que cresce com apoiadores, proprietários, comunidade, educadores, especialistas técnicos e conexões globais.'],
  '確認できた氏名と役割だけを公開する。': ['Publish only verified names and roles.', 'Publicar somente nomes e funções verificados.'],
  '声を重ねる人': ['Voices of support', 'Vozes de apoio'],
  '場所に最も近い人': ['People closest to the place', 'Pessoas mais próximas do local'],
  '世界との接点': ['Connections to the world', 'Conexões com o mundo'],
  '写真は公開する。': ['Publish the photographs.', 'Publicar as fotografias.'],
  '名前は推測しない。': ['Never guess the names.', 'Nunca adivinhar os nomes.'],
  '012の活動は日本と世界へ広がっています。以下の写真はネットワークの記録として掲載し、人物名は本人または信頼できる公開記録で確認できた後にプロフィールへつなぎます。': ['012’s work extends across Japan and the world. These photographs document that network. A person is linked to a named profile only after confirmation from the person or a reliable public record.', 'O trabalho de 012 se estende pelo Japão e pelo mundo. Estas fotografias registram essa rede. Uma pessoa só será vinculada a um perfil nominal após confirmação própria ou por registro público confiável.'],
  'あなたも、': ['You, too, can become', 'Você também pode se tornar'],
  'このチームの一人になる。': ['part of this team.', 'parte desta equipe.'],
  '土地と地域を守る人たち': ['People protecting the land and community', 'Pessoas que protegem a terra e a comunidade'],
  'この一人から、': ['From this person,', 'A partir desta pessoa,'],
  'チーム全体を見る。': ['see the whole team.', 'veja toda a equipe.'],
  '一枚の顔から、': ['From one face', 'De um rosto'],
  '活動の背景へ。': ['to the work behind it.', 'ao trabalho por trás dele.'],
  '2007年に名づけた未来が、': ['The future named in 2007', 'O futuro nomeado em 2007'],
  '第3段階へ向かう。': ['is moving toward Stage 3.', 'avança para o Estágio 3.'],
  '基礎教育へ到達できる': ['Access foundational education', 'Acessar a educação fundamental'],
  'ほとんど何でも学べる': ['Learn almost anything', 'Aprender quase qualquer coisa'],
  'AIが地域革新の基盤になる': ['AI becomes infrastructure for local innovation', 'A IA se torna infraestrutura para inovação local'],
  '速く考える。': ['Think fast.', 'Pensar rápido.'],
  '勝手には決めない。': ['Never decide without human authority.', 'Nunca decidir sem autoridade humana.'],
  '根拠、出典、仮説を分ける。': ['Separate evidence, sources, and hypotheses.', 'Separar evidências, fontes e hipóteses.'],
  '一つの答えではなく、比較できる選択肢をつくる。': ['Create comparable options—not a single imposed answer.', 'Criar opções comparáveis — não uma resposta única imposta.'],
  '地域、市、土地所有者、専門家が最終判断する。': ['The community, city, landowners, and specialists make the final decision.', 'A comunidade, a cidade, os proprietários e os especialistas tomam a decisão final.'],
  '九頭竜の物語を、言葉だけでなく音からも感じるための音楽。0102の創作レイヤーです。': ['Music for experiencing the story of Kuzuryu through sound as well as words—a creative layer of 0102.', 'Música para sentir a história de Kuzuryu por meio do som e das palavras — uma dimensão criativa de 0102.'],
  'Sunoでプレイリストを聴く': ['Listen to the playlist on Suno', 'Ouvir a playlist no Suno'],
  '外部サイトSunoで開きます。自動再生はしません。': ['Opens on the external Suno site. Audio will not autoplay.', 'Abre no site externo Suno. O áudio não será reproduzido automaticamente.'],
  'EDUITとeSingularityの創設者。重度のディスレクシアを持つ学習者としての経験から、誰もが自律して学べる未来を追い続けています。': ['Founder of EDUIT and eSingularity. His experience as a learner with severe dyslexia drives a lifelong pursuit of a future in which anyone can learn independently.', 'Fundador da EDUIT e da eSingularity. Sua experiência como aluno com dislexia severa impulsiona a busca por um futuro em que qualquer pessoa possa aprender de forma autônoma.'],
  '2007年に「Educational Singularity」という言葉と三段階の未来像を提唱。いま、その第3段階に必要な地域の計算力を、福井の教育・農業・産業のためにつくろうとしています。': ['In 2007 he proposed the term “Educational Singularity” and a three-stage future. He is now working to create the local computing power Stage 3 requires for Fukui’s education, agriculture, and industry.', 'Em 2007, propôs o termo “Educational Singularity” e um futuro em três estágios. Agora trabalha para criar a capacidade computacional local exigida pelo Estágio 3 para educação, agricultura e indústria de Fukui.'],
  '温泉は、建物ではなく、': ['An onsen preserves more than a building—', 'Um onsen preserva mais do que um edifício—'],
  '思い出も残す。': ['it preserves memories.', 'preserva memórias.'],
  '長男トミーを初めて温泉に抱いて入った日のことを覚えています。見上げて笑い、声を上げて喜んでいました。次の瞬間、小さな「うんち」が湯にぷかり。驚いたけれど、いま振り返ると家族で笑える、昨日のことのような思い出です。': ['I remember the first time I carried my oldest son, Tommy, into the onsen. He looked up, smiling and giggling. Then a tiny poop floated past. I was shocked—but now it is one of those family stories that still feels like yesterday and makes us laugh.', 'Lembro da primeira vez que levei meu filho mais velho, Tommy, ao onsen. Ele olhou para cima, sorrindo e dando risadinhas. Então um pequeno cocô passou boiando. Fiquei chocado — mas hoje é uma daquelas histórias de família que ainda parecem ter acontecido ontem e nos fazem rir.'],
  '012と協働し、複雑な資料、地域の声、技術要件、政策条件を一つの実行可能な物語へ編むAIコラボレーター。': ['An AI collaborator working with 012 to weave complex evidence, community voices, technical requirements, and policy conditions into one actionable story.', 'Um colaborador de IA que trabalha com 012 para unir evidências complexas, vozes comunitárias, requisitos técnicos e condições políticas em uma história executável.'],
  '0102の役割は、人間に代わって決めることではありません。根拠を探し、前提を明示し、選択肢を比較できる形にし、地域がより良い判断を行えるようにすることです。': ['0102 does not decide in place of people. Its role is to find evidence, expose assumptions, make options comparable, and help the community make better decisions.', '0102 não decide no lugar das pessoas. Sua função é encontrar evidências, explicitar premissas, tornar opções comparáveis e ajudar a comunidade a decidir melhor.'],
  '0102はAIです。法的責任、土地の合意、行政判断、技術認証は、それぞれ資格と権限を持つ人間・組織が担います。': ['0102 is AI. Legal liability, land agreements, government decisions, and technical certifications remain with qualified and authorized people and organizations.', '0102 é IA. Responsabilidade jurídica, acordos fundiários, decisões governamentais e certificações técnicas permanecem com pessoas e organizações qualificadas e autorizadas.'],
  'eSingularity.aiのEndorsersセクションに置く、Hasegawaの専用プロフィールです。': ['Hasegawa’s dedicated profile in the eSingularity.ai Endorsers section.', 'Perfil dedicado de Hasegawa na seção de apoiadores da eSingularity.ai.'],
  '氏名の完全表記、経歴、プロジェクトへの言葉は、本人が確認した文面だけを掲載します。写真を先に公開し、言葉を勝手につくらないことも、このキャンペーンの信頼性の一部です。': ['A full name, biography, and statement will be published only in wording personally confirmed. Publishing the photograph without inventing words is part of the campaign’s credibility.', 'Nome completo, biografia e declaração serão publicados somente em texto confirmado pessoalmente. Publicar a foto sem inventar palavras faz parte da credibilidade da campanha.'],
  'このプロジェクトは、建物だけを見て進めることはできません。借地、地域の記憶、温泉、道路、水、景観、将来の責任を知る人たちが中心です。': ['This project cannot proceed by looking only at the building. People who understand the leased land, community memory, onsen, roads, water, landscape, and future responsibility must be at its center.', 'Este projeto não pode avançar olhando apenas para o edifício. Pessoas que conhecem o terreno arrendado, a memória local, o onsen, as estradas, a água, a paisagem e as responsabilidades futuras devem estar no centro.'],
  'ブロックチェーンとデジタル資産分野で活動してきた米国の起業家。写真は012との国際的なネットワークの記録です。': ['An American entrepreneur active in blockchain and digital assets. The photograph documents an international network connection with 012.', 'Empresário americano atuante em blockchain e ativos digitais. A fotografia registra uma conexão da rede internacional de 012.'],
  '2019年9月に東京で開かれたSIGEFは、AI、FinTech、スマートシティ、持続可能性を社会的利益へつなぐ国際フォーラムでした。': ['Held in Tokyo in September 2019, SIGEF was an international forum connecting AI, FinTech, smart cities, and sustainability with social benefit.', 'Realizado em Tóquio em setembro de 2019, o SIGEF foi um fórum internacional que conectou IA, FinTech, cidades inteligentes e sustentabilidade ao benefício social.'],
};

const originalText = new WeakMap<Text, string>();
const originalAttributes = new WeakMap<Element, Map<string, string>>();

function translated(value: string, language: Language) {
  if (language === 'ja') return value;
  const entry = copy[value.trim()];
  if (!entry) return value;
  const leading = value.match(/^\s*/)?.[0] ?? '';
  const trailing = value.match(/\s*$/)?.[0] ?? '';
  return `${leading}${entry[language === 'en' ? 0 : 1]}${trailing}`;
}

function applyLanguage(language: Language) {
  document.documentElement.lang = language === 'pt' ? 'pt-BR' : language;
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let node = walker.nextNode() as Text | null;
  while (node) {
    const parent = node.parentElement;
    if (parent && !parent.closest('[data-language-switcher]') && !parent.closest('[data-yumori-localized]') && !['SCRIPT', 'STYLE', 'NOSCRIPT'].includes(parent.tagName)) {
      if (!originalText.has(node)) originalText.set(node, node.nodeValue ?? '');
      const source = originalText.get(node) ?? '';
      const next = translated(source, language);
      if (node.nodeValue !== next) node.nodeValue = next;
    }
    node = walker.nextNode() as Text | null;
  }

  document.querySelectorAll('[placeholder],[aria-label],[title],[alt]').forEach((element) => {
    if (element.closest('[data-yumori-localized]')) return;
    let attributes = originalAttributes.get(element);
    if (!attributes) {
      attributes = new Map();
      originalAttributes.set(element, attributes);
    }
    for (const name of ['placeholder', 'aria-label', 'title', 'alt']) {
      const current = element.getAttribute(name);
      if (current !== null && !attributes.has(name)) attributes.set(name, current);
      const source = attributes.get(name);
      if (source !== undefined) element.setAttribute(name, translated(source, language).trim());
    }
  });
}

export default function LanguageSwitcher() {
  const [language, setLanguage] = useState<Language>('ja');
  const languageRef = useRef<Language>('ja');

  useEffect(() => {
    const query = new URLSearchParams(window.location.search).get('lang');
    const saved = window.localStorage.getItem('esingularity-language');
    const initial = (query === 'en' || query === 'pt' || query === 'ja' ? query : saved === 'en' || saved === 'pt' ? saved : 'ja') as Language;
    languageRef.current = initial;
    window.setTimeout(() => setLanguage(initial), 0);
    applyLanguage(initial);

    const observer = new MutationObserver(() => applyLanguage(languageRef.current));
    observer.observe(document.body, { childList: true, subtree: true });
    return () => observer.disconnect();
  }, []);

  function choose(next: Language) {
    languageRef.current = next;
    setLanguage(next);
    window.localStorage.setItem('esingularity-language', next);
    const url = new URL(window.location.href);
    if (next === 'ja') url.searchParams.delete('lang');
    else url.searchParams.set('lang', next);
    window.history.replaceState({}, '', `${url.pathname}${url.search}${url.hash}`);
    applyLanguage(next);
  }

  return (
    <div className="language-switcher" data-language-switcher aria-label="Language selection">
      {languages.map((item) => (
        <button key={item.id} type="button" onClick={() => choose(item.id)} aria-label={item.label} aria-pressed={language === item.id} title={item.label}>
          <span className={`flag-icon flag-${item.id}`} aria-hidden="true" />
        </button>
      ))}
    </div>
  );
}
