// Japanese is canonical; English and Brazilian Portuguese are reviewed translations.
export const OPENING_SIGNUP_URL = 'https://docs.google.com/forms/d/e/1FAIpQLScSKFyzCym8NCarvNIa5cT9c2Pe8C-cY2AbC4zLgsDOKspYKA/viewform';
export const OPENING_IMAGE = '/vision/onsen-choice-clean.png';
export const openingCopy = {
  ja: {
    label: '旧すかっとランド九頭竜 · 地域の未来を選ぶ',
    title: '地域の心を、壊していいのでしょうか？',
    body: '人が集い、語らい、湯につかった場所。壊せば、同じ場所が戻る保証はありません。福井市は解体の前に、コンピュートを活かす再生案を調べるべきではないでしょうか。',
    mission: 'コンピュートで、温泉を救えるか。地域を再生できるか。日本のAI基盤を変えられるか。',
    join: '賛同する · YUMORI準備委員会に参加',
    vote: '福井市議会へ、解体予算に反対の声を。',
    fullscreen: '全画面で見る',
    note: '解体と再生を比べる構想図です。工事の現況や実現が決まった施設を示すものではありません。',
    alt: '同じ温泉建物の二つの未来。左は解体を想定した暗い姿、右は温泉と地域の居場所として再生する明るい構想。',
    left: '解体に、約15.8億円？', right: '地域の心を、次の世代へ',
    costNote: '2026年6月・市議会質問資料の概算。確定契約額ではありません。',
    source: '解体費の出典を見る',
    map: '土地利用の比較とJHRを見る',
  },
  en: {
    label: 'Former Sukatto Land Kuzuryu · A choice for the community',
    title: 'Should we demolish the heart of our community?',
    body: 'A place to gather, talk and share the warmth of the baths. Once demolished, there is no guarantee it will return. Shouldn’t Fukui City investigate the compute-powered reuse proposal before demolition?',
    mission: 'Can compute save an onsen, revitalize a community and reshape Japan’s AI infrastructure?',
    join: 'I agree · Join the YUMORI preparatory committee',
    vote: 'Urge Fukui City Council to oppose the demolition budget.',
    fullscreen: 'View full screen',
    note: 'Concept comparison of demolition and reuse. It does not show current construction or an approved development.',
    alt: 'Two possible futures for the same onsen: a dark demolition scenario on the left and a warmly illuminated community reuse concept on the right.',
    left: '¥1.58 billion to demolish?', right: 'A community heart for the next generation',
    costNote: 'Estimate cited in June 2026 council questions; not a final contract price.',
    source: 'See demolition estimate source',
    map: 'Explore the land-use comparison and JHR',
  },
  pt: {
    label: 'Antigo Sukatto Land Kuzuryu · Uma escolha para a comunidade',
    title: 'Devemos demolir o coração da nossa comunidade?',
    body: 'Um lugar para se encontrar, conversar e aproveitar as águas termais. Depois da demolição, não há garantia de que ele volte. A cidade de Fukui não deveria avaliar a proposta de reuso apoiada pela computação antes de demolir?',
    mission: 'A computação pode salvar um onsen, revitalizar uma comunidade e transformar a infraestrutura de IA do Japão?',
    join: 'Concordo · Participar do comitê preparatório YUMORI',
    vote: 'Peça à Câmara Municipal de Fukui que se oponha ao orçamento de demolição.',
    fullscreen: 'Ver em tela cheia',
    note: 'Comparação conceitual entre demolição e reuso. Não mostra obras em andamento nem um empreendimento aprovado.',
    alt: 'Dois futuros possíveis para o mesmo onsen: um cenário escuro de demolição à esquerda e uma proposta de reuso comunitário iluminada à direita.',
    left: '¥1,58 bilhão para demolir?', right: 'Um coração para a próxima geração',
    costNote: 'Estimativa citada nas perguntas à Câmara em junho de 2026; não é o valor final de um contrato.',
    source: 'Ver a fonte da estimativa de demolição',
    map: 'Ver a comparação de uso do solo e o JHR',
  },
};
