"""Focused model-runtime setup for OpenClaw claim-loop integration tests."""

from __future__ import annotations

import json
from unittest.mock import patch

from modules.communication.moltbot_bridge.tests.model_runtime_binding_receipt_test_helpers import (
    model_selection_and_runtime_binding_receipts,
)
from modules.communication.moltbot_bridge.tests.test_reddog_main_resident_queue_serial_loop_bootstrap import (
    _FakeModelRuntimeBindingVerifier,
)


def pin_authority_epoch_receipts(monkeypatch) -> None:
    """Pin signed receipt time to the queue-loop test authority epoch."""

    def receipts(*, runtime_surface):
        with patch(
            "modules.ai_intelligence.ai_gateway.tests."
            "model_signed_evidence_test_helpers.NOW",
            1000,
        ):
            return model_selection_and_runtime_binding_receipts(
                runtime_surface=runtime_surface, verified_at_epoch=1000
            )

    monkeypatch.setattr(
        "modules.communication.moltbot_bridge.tests."
        "model_runtime_binding_queue_test_helpers."
        "model_selection_and_runtime_binding_receipts",
        receipts,
    )


def patch_fusion_artifact_generator(monkeypatch, artifact_path: str):
    """Install bounded Fusion and runtime-verifier fakes."""

    from modules.communication.moltbot_bridge.src import (
        reddog_bounded_artifact_generation_runtime as artifact_runtime,
        reddog_main_resident_queue_serial_loop_bootstrap as bootstrap_runtime,
    )

    calls: list[dict[str, object]] = []

    def fake_fusion(api_key, user_payload, messages, payload):
        calls.append(
            {
                "api_key": api_key,
                "user_payload": user_payload,
                "messages": messages,
                "payload": payload,
            }
        )
        return {
            "ok": True,
            "content": json.dumps(
                {
                    "artifact_contents": {
                        artifact_path: "# Generated By Fusion\n\nThis text came from the bounded artifact generator.\n"
                    }
                },
                sort_keys=True,
            ),
            "review_packet": {"receipt_id": "fusion-artifact-receipt-1"},
        }

    monkeypatch.setattr(
        artifact_runtime, "_load_foundups_fusion_runner", lambda: fake_fusion
    )
    monkeypatch.setattr(
        bootstrap_runtime,
        "build_model_runtime_verifier",
        lambda **_kwargs: (_FakeModelRuntimeBindingVerifier(), ()),
    )
    monkeypatch.setenv("REDDOG_MODEL_RUNTIME_AVAILABLE_PROVIDERS", "openrouter")
    monkeypatch.setenv("REDDOG_RESIDENT_QUEUE_NOW_EPOCH", "1000")
    monkeypatch.setenv("OPENROUTER_API_KEY", "test-openrouter-key")
    return calls


__all__ = ["patch_fusion_artifact_generator", "pin_authority_epoch_receipts"]
