"""Tests for REDDOG_MAIN_OPENCLAW_SIGNED_WORKER_CLAIM_LOOP_PREFLIGHT_PHASE1."""

from __future__ import annotations

import json
import os
import sqlite3
from pathlib import Path
from unittest.mock import patch

import pytest

from modules.communication.moltbot_bridge.src import (
    reddog_openclaw_hermes_0102_worker_dispatch_runtime as runtime,
)
from modules.communication.moltbot_bridge.tests.test_reddog_main_resident_queue_serial_loop_bootstrap import (
    NOW as BOOTSTRAP_NOW,
    PILOT_ARTIFACT,
    PILOT_OPERATION,
    REDDOG_SIGNATURE_VERIFIER_BACKEND_ED25519,
    _draft_pr_publish_request,
    _ed25519_signing_material,
    _FakeWorkerDispatchTaskWriter,
    _FakeWorktreeRunner,
    _pilot_bounded_worker_plan,
    _pilot_allowed_paths,
    _pilot_path_overrides,
    _pilot_payloads,
    _pilot_worktree_path,
    _principals,
    _profile as _bootstrap_profile,
    _repo,
    _snapshot as _bootstrap_snapshot,
    _snapshots,
    _slice_verifier_request,
    _valve_environment,
    _work_order,
    _write_runtime_json,
    run_reddog_main_resident_queue_serial_loop_bootstrap,
)
from modules.communication.moltbot_bridge.tests.test_reddog_signed_worker_dispatch_task_executor import (
    _allocation,
    _FakeEnvDraftPrRunner,
    _publish_agentdb_task,
    _publish_agentdb_task_with_allocation,
)
from modules.communication.moltbot_bridge.src.reddog_resident_queue_binding_profile import (
    resident_queue_materializer_mode,
)
from modules.infrastructure.database.src.agent_db import AgentDB
from modules.infrastructure.database.src.db_manager import DatabaseManager


REPO_ROOT = Path(__file__).resolve().parents[4]
CLAIM_LOOP = (
    "modules.communication.moltbot_bridge.src.openclaw_supervisor."
    "claim_reddog_signed_worker_dispatch_tasks_until_idle"
)


def test_profile_materializer_default_does_not_conflict_with_explicit_work_orders() -> None:
    env = {
        "REDDOG_RESIDENT_QUEUE_BINDING_PROFILE": "signed_0102_bounded_code_fusion_worktree_draft_pr",
        "REDDOG_WORK_ORDERS_PATH": "O:/runtime/work_orders.json",
    }

    assert resident_queue_materializer_mode(env) == ""


def test_explicit_blank_materializer_mode_preserves_profile_default() -> None:
    env = {
        "REDDOG_RESIDENT_QUEUE_BINDING_PROFILE": "signed_0102_bounded_code_fusion_worktree_draft_pr",
        "REDDOG_WORK_ORDERS_PATH": "O:/runtime/work_orders.json",
        "REDDOG_WORK_ORDER_MATERIALIZER_MODE": "",
    }

    assert resident_queue_materializer_mode(env) == "authority_profile"


@pytest.fixture(autouse=True)
def isolated_agent_db(tmp_path, monkeypatch):
    monkeypatch.setenv("FOUNDUPS_DB_PATH", str(tmp_path / "foundups.db"))
    DatabaseManager.reset_for_tests()
    yield
    DatabaseManager.reset_for_tests()


def _patch_fusion_artifact_generator(monkeypatch) -> list[dict[str, object]]:
    from modules.communication.moltbot_bridge.src import (
        reddog_bounded_artifact_generation_runtime as artifact_runtime,
    )

    calls: list[dict[str, object]] = []

    def _fake_fusion(api_key, user_payload, messages, payload):
        calls.append(
            {
                "api_key": api_key,
                "user_payload": user_payload,
                "messages": messages,
                "payload": payload,
            }
        )
        return {
            "ok": True,
            "content": json.dumps(
                {
                    "artifact_contents": {
                        PILOT_ARTIFACT: (
                            "# Generated By Fusion\n\n"
                            "This text came from the bounded artifact generator.\n"
                        )
                    }
                },
                sort_keys=True,
            ),
            "review_packet": {"receipt_id": "fusion-artifact-receipt-1"},
        }

    monkeypatch.setattr(
        artifact_runtime,
        "_load_foundups_fusion_runner",
        lambda: _fake_fusion,
    )
    monkeypatch.setenv("OPENROUTER_API_KEY", "test-openrouter-key")
    return calls


def test_main_openclaw_signed_worker_claim_loop_disabled_by_default() -> None:
    import main

    with patch(CLAIM_LOOP, side_effect=AssertionError("claim loop must not run")):
        with patch.dict("os.environ", {}, clear=True):
            assert main.run_reddog_openclaw_signed_worker_claim_loop_preflight(REPO_ROOT) is True


def test_main_openclaw_signed_worker_claim_loop_passes_when_idle(capsys) -> None:
    import main

    with patch(
        CLAIM_LOOP,
        return_value={
            "accepted": True,
            "status": "SIGNED_WORKER_OPENCLAW_CLAIM_LOOP_IDLE",
            "claimed_count": 0,
            "completed_task_ids": (),
            "requeued_task_ids": (),
            "failed_task_ids": (),
            "rejection_reasons": ("NO_PENDING_TASK",),
        },
    ) as mocked:
        with patch.dict(
            "os.environ",
            {
                "REDDOG_OPENCLAW_SIGNED_WORKER_CLAIM_LOOP": "1",
                "OPENCLAW_SIGNED_WORKER_TASK_MAX_CLAIMS": "3",
            },
            clear=True,
        ):
            assert main.run_reddog_openclaw_signed_worker_claim_loop_preflight(REPO_ROOT) is True

    assert mocked.call_args.kwargs["repo_root"] == REPO_ROOT
    assert mocked.call_args.kwargs["max_claims"] == 3
    captured = capsys.readouterr().out
    assert "[REDDOG-OPENCLAW-CLAIM-LOOP] preflight=PASS" in captured
    assert "claimed_count=0" in captured
    assert "max_claims=3" in captured


def test_main_openclaw_signed_worker_claim_loop_profile_enables_control_plane() -> None:
    import main

    with patch(
        CLAIM_LOOP,
        return_value={
            "accepted": True,
            "status": "SIGNED_WORKER_OPENCLAW_CLAIM_LOOP_IDLE",
            "claimed_count": 0,
            "completed_task_ids": (),
            "requeued_task_ids": (),
            "failed_task_ids": (),
            "rejection_reasons": ("NO_PENDING_TASK",),
        },
    ) as mocked:
        with patch.dict(
            "os.environ",
            {"REDDOG_RESIDENT_QUEUE_BINDING_PROFILE": "signed_0102_bounded_code"},
            clear=True,
        ):
            assert main.run_reddog_openclaw_signed_worker_claim_loop_preflight(REPO_ROOT) is True

    assert mocked.call_count == 1


def test_main_openclaw_signed_worker_claim_loop_explicit_zero_overrides_profile() -> None:
    import main

    with patch(CLAIM_LOOP, side_effect=AssertionError("claim loop must not run")):
        with patch.dict(
            "os.environ",
            {
                "REDDOG_RESIDENT_QUEUE_BINDING_PROFILE": "signed_0102_bounded_code",
                "REDDOG_OPENCLAW_SIGNED_WORKER_CLAIM_LOOP": "0",
            },
            clear=True,
        ):
            assert main.run_reddog_openclaw_signed_worker_claim_loop_preflight(REPO_ROOT) is True


def test_main_openclaw_signed_worker_claim_loop_blocks_when_enforced() -> None:
    import main

    with patch(
        CLAIM_LOOP,
        return_value={
            "accepted": False,
            "status": "SIGNED_WORKER_OPENCLAW_CLAIM_LOOP_REJECT",
            "claimed_count": 0,
            "completed_task_ids": (),
            "requeued_task_ids": (),
            "failed_task_ids": ("task-1",),
            "rejection_reasons": ("CLAIM_REJECTED",),
        },
    ):
        with patch.dict(
            "os.environ",
            {
                "REDDOG_OPENCLAW_SIGNED_WORKER_CLAIM_LOOP": "1",
                "REDDOG_OPENCLAW_SIGNED_WORKER_CLAIM_LOOP_ENFORCED": "1",
            },
            clear=True,
        ):
            assert main.run_reddog_openclaw_signed_worker_claim_loop_preflight(REPO_ROOT) is False


def test_main_openclaw_signed_worker_claim_loop_rejects_invalid_max_claims_when_enforced() -> None:
    import main

    with patch(CLAIM_LOOP, side_effect=AssertionError("claim loop must not run")):
        with patch.dict(
            "os.environ",
            {
                "REDDOG_OPENCLAW_SIGNED_WORKER_CLAIM_LOOP": "1",
                "REDDOG_OPENCLAW_SIGNED_WORKER_CLAIM_LOOP_ENFORCED": "1",
                "OPENCLAW_SIGNED_WORKER_TASK_MAX_CLAIMS": "0",
            },
            clear=True,
        ):
            assert main.run_reddog_openclaw_signed_worker_claim_loop_preflight(REPO_ROOT) is False


def test_main_openclaw_signed_worker_claim_loop_exception_is_nonblocking_by_default() -> None:
    import main

    with patch(CLAIM_LOOP, side_effect=RuntimeError("agentdb unavailable")):
        with patch.dict(
            "os.environ",
            {"REDDOG_OPENCLAW_SIGNED_WORKER_CLAIM_LOOP": "1"},
            clear=True,
        ):
            assert main.run_reddog_openclaw_signed_worker_claim_loop_preflight(REPO_ROOT) is True


def test_main_openclaw_signed_worker_claim_loop_runs_real_agentdb_queue_stage(
    tmp_path: Path,
    monkeypatch,
    capsys,
) -> None:
    import main

    repo = _repo(tmp_path)
    principal_public, reddog_public, connector = _ed25519_signing_material()
    pilot_overrides = _pilot_path_overrides()
    state = _write_runtime_json(tmp_path, "work_state.json", _bootstrap_snapshot())
    profile = _write_runtime_json(
        tmp_path,
        "profile.json",
        _bootstrap_profile(
            principal_public_key=principal_public,
            reddog_public_key=reddog_public,
            requested_operation=PILOT_OPERATION,
            allowed_paths=_pilot_allowed_paths(),
            denied_paths=pilot_overrides["denied_paths"],
        ),
    )
    snapshots = _write_runtime_json(tmp_path, "snapshots.json", _snapshots())
    principals = _write_runtime_json(tmp_path, "principals.json", _principals(principal_public))
    work_order = _work_order(
        **pilot_overrides,
        bounded_worker_plan=_pilot_bounded_worker_plan(),
    )
    work_order["holoindex_evidence"] = {
        **dict(work_order["holoindex_evidence"]),
        "holoindex_freshness_receipt_digest": "sha256:holo-fresh",
    }
    work_orders = _write_runtime_json(
        tmp_path,
        "work_orders.json",
        {"work_orders": {str(work_order["work_order_id"]): work_order}},
    )
    valve_env = _write_runtime_json(tmp_path, "valve_env.json", _valve_environment())
    chain = tmp_path / "runtime" / "chain_results.json"
    authority_state = tmp_path / "runtime" / "authority_state.json"
    socket_path = tmp_path / "runtime" / "signer.sock"
    worktree_runner = _FakeWorktreeRunner()
    worktree = _pilot_worktree_path(repo, work_order)

    seed = run_reddog_main_resident_queue_serial_loop_bootstrap(
        repo_root=repo,
        work_state_path=state,
        chain_results_path=chain,
        authority_profile_path=profile,
        work_orders_path=work_orders,
        valve_environment_path=valve_env,
        authority_state_path=authority_state,
        permission_snapshots_path=snapshots,
        principal_authority_records_path=principals,
        signer_socket_path=socket_path,
        signer_socket_connector=connector,
        signature_verifier_backend=REDDOG_SIGNATURE_VERIFIER_BACKEND_ED25519,
        worker_dispatch_writer=_FakeWorkerDispatchTaskWriter(),
        worktree_runner=worktree_runner,
        now_iso=BOOTSTRAP_NOW,
        now_epoch=1000,
        requested_queue_item_id="queue-1",
        max_steps=9,
    )
    assert seed.accepted is True
    assert seed.dispatched_stages[-1] == "worktree_create"
    assert worktree.exists()
    assert not (worktree / PILOT_ARTIFACT).exists()

    pilot_payloads = _pilot_payloads(repo, worktree, work_order)
    generic_writer = _write_runtime_json(
        tmp_path,
        "generic_writer.json",
        pilot_payloads["generic_writer_dryrun_result"],
    )
    governed_shell = _write_runtime_json(
        tmp_path,
        "governed_shell.json",
        pilot_payloads["governed_shell_dryrun_result"],
    )
    artifacts = _write_runtime_json(
        tmp_path,
        "artifact_contents.json",
        pilot_payloads["artifact_contents"],
    )
    holoindex = _write_runtime_json(
        tmp_path,
        "holoindex_evidence.json",
        pilot_payloads["holoindex_evidence"],
    )

    task_id = _publish_agentdb_task()
    monkeypatch.setenv("REDDOG_OPENCLAW_SIGNED_WORKER_CLAIM_LOOP", "1")
    monkeypatch.setenv("OPENCLAW_SIGNED_WORKER_TASK_MAX_CLAIMS", "1")
    monkeypatch.setenv("REDDOG_SIGNED_WORKER_QUEUE_LOOP_RUNNER", "1")
    monkeypatch.setenv("REDDOG_AUTHORITATIVE_WORK_STATE_PATH", str(state))
    monkeypatch.setenv("REDDOG_RESIDENT_QUEUE_CHAIN_RESULTS_PATH", str(chain))
    monkeypatch.setenv("REDDOG_RESIDENT_QUEUE_AUTHORITY_PROFILE_PATH", str(profile))
    monkeypatch.setenv("REDDOG_WORK_ORDERS_PATH", str(work_orders))
    monkeypatch.setenv("REDDOG_GENERIC_WRITER_DRYRUN_RESULT_PATH", str(generic_writer))
    monkeypatch.setenv("REDDOG_GOVERNED_SHELL_DRYRUN_RESULT_PATH", str(governed_shell))
    monkeypatch.setenv("REDDOG_ARTIFACT_CONTENTS_PATH", str(artifacts))
    monkeypatch.setenv("REDDOG_HOLOINDEX_EVIDENCE_PATH", str(holoindex))
    monkeypatch.setenv("REDDOG_SIGNED_WORKER_QUEUE_LOOP_MAX_STEPS", "1")
    monkeypatch.setenv("REDDOG_RESIDENT_QUEUE_NOW_ISO", BOOTSTRAP_NOW)

    assert main.run_reddog_openclaw_signed_worker_claim_loop_preflight(repo) is True

    captured = capsys.readouterr().out
    assert "[REDDOG-OPENCLAW-CLAIM-LOOP] preflight=PASS" in captured
    assert "status=SIGNED_WORKER_OPENCLAW_CLAIM_LOOP_ACCEPT" in captured
    assert "claimed_count=1" in captured
    assert f"requeued={task_id}" in captured
    assert AgentDB().get_autonomous_task_by_id(task_id)["status"] == "pending"

    stored = json.loads(chain.read_text(encoding="utf-8"))
    stage = stored["stage_results"]["bounded_worker_pilot"]
    assert stage["decision"] == "QUEUE_AUTHORIZED_BOUNDED_WORKER_PILOT_INVOKE_ACCEPT"
    assert stage["bounded_task_execution_performed"] is True
    assert stage["bounded_file_edit_performed"] is True
    assert stage["shell_command_executed"] is False
    assert stage["openclaw_enqueue_performed"] is False
    assert stage["hermes_dispatch_performed"] is False
    assert stage["holoindex_reindex_performed"] is False
    assert (worktree / PILOT_ARTIFACT).read_text(encoding="utf-8").startswith(
        "# Resident Queue Pilot"
    )
    assert not (repo / PILOT_ARTIFACT).exists()


def test_main_openclaw_signed_0102_bounded_code_uses_fusion_artifact_generation(
    tmp_path: Path,
    monkeypatch,
    capsys,
) -> None:
    import main

    repo = _repo(tmp_path)
    principal_public, reddog_public, connector = _ed25519_signing_material()
    pilot_overrides = _pilot_path_overrides()
    state = _write_runtime_json(tmp_path, "work_state.json", _bootstrap_snapshot())
    profile = _write_runtime_json(
        tmp_path,
        "profile.json",
        _bootstrap_profile(
            principal_public_key=principal_public,
            reddog_public_key=reddog_public,
            requested_operation=PILOT_OPERATION,
            allowed_paths=_pilot_allowed_paths(),
            denied_paths=pilot_overrides["denied_paths"],
        ),
    )
    snapshots = _write_runtime_json(tmp_path, "snapshots.json", _snapshots())
    principals = _write_runtime_json(tmp_path, "principals.json", _principals(principal_public))
    work_order = _work_order(
        **pilot_overrides,
        bounded_worker_plan=_pilot_bounded_worker_plan(),
    )
    work_order["holoindex_evidence"] = {
        **dict(work_order["holoindex_evidence"]),
        "holoindex_freshness_receipt_digest": "sha256:holo-fresh",
    }
    work_orders = _write_runtime_json(
        tmp_path,
        "work_orders.json",
        {"work_orders": {str(work_order["work_order_id"]): work_order}},
    )
    valve_env = _write_runtime_json(tmp_path, "valve_env.json", _valve_environment())
    chain = tmp_path / "runtime" / "chain_results.json"
    authority_state = tmp_path / "runtime" / "authority_state.json"
    socket_path = tmp_path / "runtime" / "signer.sock"
    worktree_runner = _FakeWorktreeRunner()
    worktree = _pilot_worktree_path(repo, work_order)

    seed = run_reddog_main_resident_queue_serial_loop_bootstrap(
        repo_root=repo,
        work_state_path=state,
        chain_results_path=chain,
        authority_profile_path=profile,
        work_orders_path=work_orders,
        valve_environment_path=valve_env,
        authority_state_path=authority_state,
        permission_snapshots_path=snapshots,
        principal_authority_records_path=principals,
        signer_socket_path=socket_path,
        signer_socket_connector=connector,
        signature_verifier_backend=REDDOG_SIGNATURE_VERIFIER_BACKEND_ED25519,
        worker_dispatch_writer=_FakeWorkerDispatchTaskWriter(),
        worktree_runner=worktree_runner,
        now_iso=BOOTSTRAP_NOW,
        now_epoch=1000,
        requested_queue_item_id="queue-1",
        max_steps=9,
    )
    assert seed.accepted is True
    assert seed.dispatched_stages[-1] == "worktree_create"
    assert worktree.exists()
    assert not (worktree / PILOT_ARTIFACT).exists()

    calls = _patch_fusion_artifact_generator(monkeypatch)
    task_id = _publish_agentdb_task_with_allocation(
        _allocation(),
        intent_id="worker_dispatch_intent_coding_worker_1",
        role="coding_worker_1",
        worker_runtime="0102",
        capability="bounded_code_change",
    )
    monkeypatch.setenv("REDDOG_OPENCLAW_SIGNED_WORKER_CLAIM_LOOP", "1")
    monkeypatch.setenv("OPENCLAW_SIGNED_0102_BOUNDED_CODE_TASKS_ENABLED", "1")
    monkeypatch.setenv("REDDOG_SIGNED_WORKER_QUEUE_LOOP_RUNNER", "1")
    monkeypatch.setenv("REDDOG_PILOT_DRYRUN_BINDING", "1")
    monkeypatch.setenv("REDDOG_ARTIFACT_GENERATION_REQUEST_BINDING", "1")
    monkeypatch.setenv("REDDOG_ARTIFACT_GENERATOR_MODE", "foundups_fusion")
    monkeypatch.setenv("OPENCLAW_SIGNED_WORKER_TASK_MAX_CLAIMS", "1")
    monkeypatch.setenv("WRE_MOCK_SKILLS", runtime.SIGNED_WORKER_DISPATCH_TASK_SKILL)
    monkeypatch.setenv("REDDOG_AUTHORITATIVE_WORK_STATE_PATH", str(state))
    monkeypatch.setenv("REDDOG_RESIDENT_QUEUE_CHAIN_RESULTS_PATH", str(chain))
    monkeypatch.setenv("REDDOG_RESIDENT_QUEUE_AUTHORITY_PROFILE_PATH", str(profile))
    monkeypatch.setenv("REDDOG_WORK_ORDERS_PATH", str(work_orders))
    monkeypatch.setenv("REDDOG_RESIDENT_QUEUE_NOW_ISO", BOOTSTRAP_NOW)

    assert main.run_reddog_openclaw_signed_worker_claim_loop_preflight(repo) is True

    captured = capsys.readouterr().out
    assert "[REDDOG-OPENCLAW-CLAIM-LOOP] preflight=PASS" in captured
    assert "status=SIGNED_WORKER_OPENCLAW_CLAIM_LOOP_ACCEPT" in captured
    assert "claimed_count=1" in captured
    assert f"completed={task_id}" in captured
    assert "requeued=(none)" in captured
    assert AgentDB().get_autonomous_task_by_id(task_id)["status"] == "completed"
    assert calls
    assert calls[0]["api_key"] == "test-openrouter-key"
    payload = calls[0]["payload"]
    assert isinstance(payload, dict)
    assert payload["mode"] == "foundups_fusion"
    assert payload["response_contract"] == "strict_json_bounded_artifact_contents.v1"
    assert "artifact_generation_binding" in payload["bridge_meta"]

    stored = json.loads(chain.read_text(encoding="utf-8"))
    stage = stored["stage_results"]["bounded_worker_pilot"]
    assert stage["decision"] == "QUEUE_AUTHORIZED_BOUNDED_WORKER_PILOT_INVOKE_ACCEPT"
    generation = stage["artifact_generation_result"]
    assert generation["accepted"] is True
    assert generation["receipt"]["model_receipt_id"] == "fusion-artifact-receipt-1"
    assert generation["model_result"]["made_network_call"] is True
    assert (worktree / PILOT_ARTIFACT).read_text(encoding="utf-8").startswith(
        "# Generated By Fusion"
    )
    assert not (repo / PILOT_ARTIFACT).exists()
    assert "REDDOG_ARTIFACT_CONTENTS_PATH" not in os.environ


def test_main_openclaw_signed_worker_claim_loop_completes_env_bound_chain(
    tmp_path: Path,
    monkeypatch,
    capsys,
) -> None:
    import main
    from modules.foundups.agent.src import worktree_pr_runner

    _FakeEnvDraftPrRunner.instances.clear()
    monkeypatch.setattr(worktree_pr_runner, "RealWorktreeRunner", _FakeEnvDraftPrRunner)
    repo = _repo(tmp_path)
    principal_public, reddog_public, connector = _ed25519_signing_material()
    pilot_overrides = _pilot_path_overrides()
    state = _write_runtime_json(tmp_path, "work_state.json", _bootstrap_snapshot())
    profile = _write_runtime_json(
        tmp_path,
        "profile.json",
        _bootstrap_profile(
            principal_public_key=principal_public,
            reddog_public_key=reddog_public,
            requested_operation=PILOT_OPERATION,
            allowed_paths=_pilot_allowed_paths(),
            denied_paths=pilot_overrides["denied_paths"],
        ),
    )
    snapshots = _write_runtime_json(tmp_path, "snapshots.json", _snapshots())
    principals = _write_runtime_json(tmp_path, "principals.json", _principals(principal_public))
    work_order = _work_order(
        **pilot_overrides,
        bounded_worker_plan=_pilot_bounded_worker_plan(),
    )
    work_order["holoindex_evidence"] = {
        **dict(work_order["holoindex_evidence"]),
        "holoindex_freshness_receipt_digest": "sha256:holo-fresh",
    }
    work_orders = _write_runtime_json(
        tmp_path,
        "work_orders.json",
        {"work_orders": {str(work_order["work_order_id"]): work_order}},
    )
    valve_env = _write_runtime_json(tmp_path, "valve_env.json", _valve_environment())
    chain = tmp_path / "runtime" / "chain_results.json"
    authority_state = tmp_path / "runtime" / "authority_state.json"
    socket_path = tmp_path / "runtime" / "signer.sock"
    worktree_runner = _FakeWorktreeRunner()
    worktree = _pilot_worktree_path(repo, work_order)

    seed = run_reddog_main_resident_queue_serial_loop_bootstrap(
        repo_root=repo,
        work_state_path=state,
        chain_results_path=chain,
        authority_profile_path=profile,
        work_orders_path=work_orders,
        valve_environment_path=valve_env,
        authority_state_path=authority_state,
        permission_snapshots_path=snapshots,
        principal_authority_records_path=principals,
        signer_socket_path=socket_path,
        signer_socket_connector=connector,
        signature_verifier_backend=REDDOG_SIGNATURE_VERIFIER_BACKEND_ED25519,
        worker_dispatch_writer=runtime.AgentDbSignedWorkerDispatchTaskWriter(),
        worktree_runner=worktree_runner,
        now_iso=BOOTSTRAP_NOW,
        now_epoch=1000,
        requested_queue_item_id="queue-1",
        max_steps=9,
    )
    assert seed.accepted is True
    assert seed.dispatched_stages[-1] == "worktree_create"

    calls = _patch_fusion_artifact_generator(monkeypatch)
    verifier_request = _write_runtime_json(
        tmp_path,
        "verifier_request.json",
        _slice_verifier_request(),
    )
    publish_request = _write_runtime_json(
        tmp_path,
        "publish_request.json",
        _draft_pr_publish_request(worktree),
    )
    outcome_store = tmp_path / "runtime" / "outcomes" / "signed-worker-ratchet.jsonl"
    pattern_memory_db = tmp_path / "runtime" / "pattern_memory.db"

    pending = AgentDB().get_autonomous_tasks(status="pending", limit=10)
    signed_tasks = [
        task
        for task in pending
        if task.get("discovered_by") == runtime.SIGNED_WORKER_DISPATCH_TASK_SOURCE
    ]
    assert len(signed_tasks) == 2
    coding_task_id = next(
        task["task_id"]
        for task in signed_tasks
        if task["context"]["worker_runtime"] == "0102"
        and task["context"]["capability"] == "bounded_code_change"
    )
    queue_stage_task_id = next(
        task["task_id"]
        for task in signed_tasks
        if task["context"]["worker_runtime"] == "openclaw"
        and task["context"]["capability"] == "queue_stage_progress"
    )
    monkeypatch.setenv("REDDOG_OPENCLAW_SIGNED_WORKER_CLAIM_LOOP", "1")
    monkeypatch.setenv("OPENCLAW_SIGNED_0102_BOUNDED_CODE_TASKS_ENABLED", "1")
    monkeypatch.setenv("OPENCLAW_SIGNED_QUEUE_STAGE_TASKS_ENABLED", "1")
    monkeypatch.setenv("OPENCLAW_SIGNED_WORKER_TASK_MAX_CLAIMS", "7")
    monkeypatch.setenv("WRE_MOCK_SKILLS", runtime.SIGNED_WORKER_DISPATCH_TASK_SKILL)
    monkeypatch.setenv("REDDOG_SIGNED_WORKER_QUEUE_LOOP_RUNNER", "1")
    monkeypatch.setenv("REDDOG_AUTHORITATIVE_WORK_STATE_PATH", str(state))
    monkeypatch.setenv("REDDOG_RESIDENT_QUEUE_CHAIN_RESULTS_PATH", str(chain))
    monkeypatch.setenv("REDDOG_RESIDENT_QUEUE_AUTHORITY_PROFILE_PATH", str(profile))
    monkeypatch.setenv("REDDOG_WORK_ORDERS_PATH", str(work_orders))
    monkeypatch.setenv("REDDOG_PILOT_DRYRUN_BINDING", "1")
    monkeypatch.setenv("REDDOG_ARTIFACT_GENERATION_REQUEST_BINDING", "1")
    monkeypatch.setenv("REDDOG_ARTIFACT_GENERATOR_MODE", "foundups_fusion")
    monkeypatch.setenv("REDDOG_SLICE_VERIFIER_REQUEST_PATH", str(verifier_request))
    monkeypatch.setenv("REDDOG_DRAFT_PR_PUBLISH_REQUEST_PATH", str(publish_request))
    monkeypatch.setenv("REDDOG_DRAFT_PR_RUNNER_MODE", "real")
    monkeypatch.setenv("REDDOG_DRAFT_PR_RUNNER_TIMEOUT_S", "88")
    monkeypatch.setenv("REDDOG_OUTCOME_RATCHET_REQUEST_BINDING", "1")
    monkeypatch.setenv("REDDOG_OUTCOME_RATCHET_STORE_PATH", str(outcome_store))
    monkeypatch.setenv("REDDOG_HELD_OUT_GATE_REQUEST_BINDING", "1")
    monkeypatch.setenv("REDDOG_PATTERN_MEMORY_ADMISSION_REQUEST_BINDING", "1")
    monkeypatch.setenv("REDDOG_PATTERN_MEMORY_ADMISSION_DB_PATH", str(pattern_memory_db))
    monkeypatch.setenv("REDDOG_SIGNED_WORKER_QUEUE_LOOP_MAX_STEPS", "1")
    monkeypatch.setenv("REDDOG_RESIDENT_QUEUE_NOW_ISO", BOOTSTRAP_NOW)

    assert main.run_reddog_openclaw_signed_worker_claim_loop_preflight(repo) is True

    captured = capsys.readouterr().out
    assert "[REDDOG-OPENCLAW-CLAIM-LOOP] preflight=PASS" in captured
    assert "status=SIGNED_WORKER_OPENCLAW_CLAIM_LOOP_ACCEPT" in captured
    assert "claimed_count=7" in captured
    assert f"completed={coding_task_id},{queue_stage_task_id}" in captured
    assert AgentDB().get_autonomous_task_by_id(coding_task_id)["status"] == "completed"
    assert AgentDB().get_autonomous_task_by_id(queue_stage_task_id)["status"] == "completed"
    remaining_signed = [
        task
        for task in AgentDB().get_autonomous_tasks(status="pending", limit=10)
        if task.get("discovered_by") == runtime.SIGNED_WORKER_DISPATCH_TASK_SOURCE
    ]
    assert remaining_signed == []
    assert calls
    assert calls[0]["api_key"] == "test-openrouter-key"

    stored = json.loads(chain.read_text(encoding="utf-8"))
    for stage_name in (
        "bounded_worker_pilot",
        "slice_verifier",
        "verified_draft_pr_publish",
        "verified_outcome_ratchet",
        "model_feedback_admission",
        "held_out_regression_gate",
        "pattern_memory_admission",
    ):
        assert stage_name in stored["stage_results"]
    generation = stored["stage_results"]["bounded_worker_pilot"]["artifact_generation_result"]
    assert generation["accepted"] is True
    assert generation["receipt"]["model_receipt_id"] == "fusion-artifact-receipt-1"
    assert stored["receipts"][-1]["next_action"] == "STOP_QUEUE_CHAIN_COMPLETE"
    assert (worktree / PILOT_ARTIFACT).read_text(encoding="utf-8").startswith(
        "# Generated By Fusion"
    )
    assert not (repo / PILOT_ARTIFACT).exists()
    assert "REDDOG_ARTIFACT_CONTENTS_PATH" not in os.environ
    draft_pr_calls = [
        call[0]
        for instance in _FakeEnvDraftPrRunner.instances
        for call in instance.calls
    ]
    assert draft_pr_calls == ["push_branch", "create_draft_pr"]
    assert outcome_store.exists()
    with sqlite3.connect(pattern_memory_db) as conn:
        count = conn.execute("SELECT COUNT(*) FROM skill_outcomes").fetchone()[0]
    assert count == 1
    assert not (repo / "runtime" / "pattern_memory.db").exists()
