"""Focused resident-queue model runtime artifact integration coverage."""

from pathlib import Path

import pytest

from modules.ai_intelligence.ai_gateway.src.model_runtime_binding_verified_admission import (
    discard_verified_runtime_binding_capability,
    verified_runtime_binding_receipt,
)
from modules.communication.moltbot_bridge.tests.model_runtime_binding_receipt_test_helpers import (
    model_runtime_binding_test_capability,
    model_runtime_binding_test_verifier,
    model_selection_and_runtime_binding_receipts,
)
from modules.communication.moltbot_bridge.src.reddog_artifact_generation_admission_capability import (
    _issue_artifact_generation_authority,
)
from modules.communication.moltbot_bridge.src import (
    reddog_bounded_artifact_generation_runtime,
)
from modules.communication.moltbot_bridge.src.reddog_bounded_artifact_generation_runtime import (
    FoundupsFusionArtifactGenerationRunner,
    generate_bounded_artifact_contents,
)
from modules.communication.moltbot_bridge.src.reddog_resident_queue_bounded_worker_pilot_handler import (
    BOUNDED_WORKER_PILOT_STAGE_KEY,
    build_reddog_resident_queue_bounded_worker_pilot_stage_handler,
)
from modules.communication.moltbot_bridge.src.reddog_resident_queue_next_stage_dispatch import (
    invoke_reddog_resident_queue_next_stage_dispatch,
)
from modules.communication.moltbot_bridge.tests.model_runtime_binding_queue_test_helpers import (
    model_bound_profile,
    model_bound_snapshot,
    model_bound_work_order,
)
from modules.communication.moltbot_bridge.src.reddog_model_runtime_verifier_bootstrap import (
    build_model_runtime_verifier,
)
from modules.communication.moltbot_bridge.tests.test_reddog_main_resident_queue_serial_loop_bootstrap import (
    NOW,
    REDDOG_SIGNATURE_VERIFIER_BACKEND_ED25519,
    RUNTIME_SURFACE_ARTIFACT_GENERATION,
    WORK_ORDER_ID,
    _FakeArtifactGenerator,
    _FakeModelRuntimeBindingVerifier,
    _FakeWorkerDispatchTaskWriter,
    _FakeWorktreeRunner,
    _assert_bootstrap_yielded_at_assurance,
    _ed25519_signing_material,
    _pilot_path_overrides,
    _pilot_payloads,
    _pilot_worktree_path,
    _principals,
    _repo,
    _snapshots,
    _valve_environment,
    _write_runtime_json,
    run_reddog_main_resident_queue_serial_loop_bootstrap,
)
from modules.communication.moltbot_bridge.tests.test_reddog_resident_queue_bounded_worker_pilot_handler import (
    _Resolver,
    _binding_stage_overrides,
    _seeded_store,
    _snapshot as _handler_snapshot,
    _valid_bundle,
    _work_order_with_plan,
)
from modules.communication.moltbot_bridge.tests.test_reddog_architect_fix_signed_wsp15_work_order_promotion import (
    _promote,
)


def test_bootstrap_generates_model_bound_artifacts_before_pilot(
    tmp_path: Path,
) -> None:
    repo = _repo(tmp_path)
    principal_public, reddog_public, connector = _ed25519_signing_material()
    selection, binding = model_selection_and_runtime_binding_receipts(
        runtime_surface=RUNTIME_SURFACE_ARTIFACT_GENERATION
    )
    verification = verified_runtime_binding_receipt(binding)
    assert verification is not None
    snapshot = model_bound_snapshot(selection, binding, verification)
    state = _write_runtime_json(tmp_path, "work_state.json", snapshot)
    overrides = _pilot_path_overrides()
    profile = _write_runtime_json(
        tmp_path,
        "profile.json",
        model_bound_profile(
            principal_public, reddog_public, selection, binding, verification, overrides
        ),
    )
    work_order = model_bound_work_order(
        selection, binding, verification, overrides
    )
    paths = _runtime_paths(tmp_path, repo, work_order, principal_public)
    artifact_generator = _FakeArtifactGenerator(content="# generated by bootstrap\n")
    result = _run_bootstrap(
        repo, state, profile, paths, connector, artifact_generator
    )
    _assert_bootstrap_yielded_at_assurance(result, paths["chain"])
    assert artifact_generator.calls == []


def test_malformed_model_runtime_verifier_config_fails_closed(
    tmp_path: Path,
) -> None:
    verifier, reasons = build_model_runtime_verifier(
        repo_root=tmp_path / "repo",
        runtime_root=tmp_path / "runtime",
        config={"unexpected_authority_field": "attacker"},
        trusted_now=lambda: 1000,
        artifact_generator=object(),
    )

    assert verifier is None
    assert reasons == ("malformed_model_runtime_verifier_config",)


def test_assigned_worker_reverifies_signed_model_evidence_before_provider(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    bundle = _valid_bundle(tmp_path)
    work_order = _work_order_with_plan(bundle)
    runtime_binding = work_order["model_runtime_binding_receipt"]
    verification = verified_runtime_binding_receipt(runtime_binding)
    verifier = model_runtime_binding_test_verifier(runtime_binding)
    assert verification is not None and verifier is not None
    probe = verifier.verify(
        binding=runtime_binding,
        selection=work_order["model_selection_receipt"],
    )
    discard_verified_runtime_binding_capability(probe)
    chain_store = _seeded_store(bundle, **_binding_stage_overrides())
    provider_calls: list[dict[str, object]] = []

    monkeypatch.setenv("OPENROUTER_API_KEY", "test-key")
    monkeypatch.setattr(
        reddog_bounded_artifact_generation_runtime,
        "_load_foundups_fusion_runner",
        lambda: _provider_stub(provider_calls),
    )
    handler = build_reddog_resident_queue_bounded_worker_pilot_stage_handler(
        chain_results_store=chain_store,
        work_order_resolver=_Resolver(work_order),
        generic_writer_dryrun_result=bundle["generic_writer_dryrun_result"],
        governed_shell_dryrun_result=bundle["governed_shell_dryrun_result"],
        artifact_contents={},
        artifact_generation_request_binding_enabled=True,
        artifact_generator=FoundupsFusionArtifactGenerationRunner(
            runtime_mode="foundups_fusion"
        ),
        model_runtime_binding_verifier=verifier,
        repo_root=bundle["repo_root"],
    )

    result = invoke_reddog_resident_queue_next_stage_dispatch(
        explicit_resident_queue_stage_dispatch_requested=True,
        work_state_snapshot=_handler_snapshot(),
        store=chain_store,
        handlers={BOUNDED_WORKER_PILOT_STAGE_KEY: handler},
        now_iso="2026-07-14T00:00:00+00:00",
    )

    assert result.accepted is True, result.rejection_reasons
    assert len(provider_calls) == 1
    bridge_meta = provider_calls[0]["bridge_meta"]
    assert (
        bridge_meta["model_runtime_binding_verification_receipt_id"]
        == verification.receipt_id
    )
    stage = chain_store.load()["stage_results"][BOUNDED_WORKER_PILOT_STAGE_KEY]
    generation = stage["artifact_generation_result"]["receipt"]
    assert (
        generation["model_runtime_binding_verification_receipt_id"]
        == verification.receipt_id
    )


def test_promoted_artifact_runtime_lineage_reaches_exact_provider(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    selection, binding = model_selection_and_runtime_binding_receipts(
        runtime_surface=RUNTIME_SURFACE_ARTIFACT_GENERATION,
        task_family="reddog_architect_fix_promotion",
    )
    promoted, store = _promote(
        model_selection_receipt=selection,
        model_runtime_binding_receipt=binding,
    )
    assert promoted.accepted is True, promoted.rejection_reasons
    assert store.load()["wre_queue_items"][0]["model_runtime_binding_receipt_id"] == (
        binding["receipt_id"]
    )
    request = _promotion_artifact_request(promoted.authority_profile)
    provider_calls: list[dict[str, object]] = []
    monkeypatch.setenv("OPENROUTER_API_KEY", "test-key")
    monkeypatch.setattr(
        reddog_bounded_artifact_generation_runtime,
        "_load_foundups_fusion_runner",
        lambda: _provider_stub(provider_calls),
    )
    result = generate_bounded_artifact_contents(
        request,
        runner=FoundupsFusionArtifactGenerationRunner(
            runtime_mode="foundups_fusion"
        ),
        authority_capability=_issue_artifact_generation_authority(request),
        model_runtime_binding_capability=model_runtime_binding_test_capability(
            selection, binding
        ),
    )
    assert result.accepted is True, result.rejection_reasons
    assert len(provider_calls) == 1
    assert provider_calls[0]["lead_model"] == binding["principal_model"]


def _promotion_artifact_request(profile):
    planned = (
        "modules/communication/moltbot_bridge/tests/fixtures/"
        "reddog_queue_pilot/README.md"
    )
    return {
        "explicit_artifact_generation_requested": True,
        "work_order_id": profile["work_order_id"],
        "slice_name": "REDDOG_NEXT_OPERATIONAL_SLICE_PHASE1",
        "task_summary": profile["task_summary"],
        "planned_artifacts": [planned],
        "evidence_context": "Promotion-derived bounded artifact generation.",
        "holoindex_evidence": {
            "index_gap_detected": False,
            "retrieval_quality": "HIGH",
        },
        "signed_authority": _promotion_model_lineage(profile),
        "signed_receipt_chain": {"accepted": True},
        "model_selection_receipt": profile["model_selection_receipt"],
        "model_runtime_binding_receipt": profile["model_runtime_binding_receipt"],
    }


def _promotion_model_lineage(profile):
    return {
        "accepted": True,
        "model_selection_receipt_id": profile["model_selection_receipt_id"],
        "model_selection_digest": profile["model_selection_digest"],
        "model_runtime_binding_receipt_id": profile[
            "model_runtime_binding_receipt_id"
        ],
        "model_runtime_binding_digest": profile["model_runtime_binding_digest"],
        "model_runtime_binding_verification_receipt_id": profile[
            "model_runtime_binding_verification_receipt_id"
        ],
        "model_runtime_binding_verification_digest": profile[
            "model_runtime_binding_verification_digest"
        ],
    }


def _provider_stub(calls):
    def run(_api_key, _prompt, _messages, payload):
        calls.append(dict(payload))
        return {
            "ok": True,
            "content": (
                '{"artifact_contents":{'
                '"modules/communication/moltbot_bridge/tests/fixtures/'
                'reddog_queue_pilot/README.md":"# generated\\n"}}'
            ),
            "review_packet": {"receipt_id": "fusion-review:integration"},
        }

    return run


def _run_bootstrap(repo, state, profile, paths, connector, artifact_generator):
    return run_reddog_main_resident_queue_serial_loop_bootstrap(
        repo_root=repo,
        work_state_path=state,
        chain_results_path=paths["chain"],
        authority_profile_path=profile,
        work_orders_path=paths["work_orders"],
        valve_environment_path=paths["valve_env"],
        generic_writer_dryrun_result_path=paths["generic_writer"],
        governed_shell_dryrun_result_path=paths["governed_shell"],
        artifact_generation_request_binding_enabled=True,
        holoindex_evidence_path=paths["holoindex"],
        authority_state_path=paths["authority_state"],
        permission_snapshots_path=paths["snapshots"],
        principal_authority_records_path=paths["principals"],
        signer_socket_path=paths["socket_path"],
        signer_socket_connector=connector,
        signature_verifier_backend=REDDOG_SIGNATURE_VERIFIER_BACKEND_ED25519,
        worker_dispatch_writer=_FakeWorkerDispatchTaskWriter(),
        worktree_runner=_FakeWorktreeRunner(),
        artifact_generator=artifact_generator,
        model_runtime_binding_verifier=_FakeModelRuntimeBindingVerifier(),
        now_iso=NOW,
        now_epoch=1000,
        trusted_now_epoch=lambda: 1000,
        requested_queue_item_id="queue-1",
        max_steps=11,
    )


def _runtime_paths(tmp_path: Path, repo: Path, work_order, principal_public):
    worktree = _pilot_worktree_path(repo, work_order)
    payloads = _pilot_payloads(repo, worktree, work_order)
    return {
        "work_orders": _write_runtime_json(
            tmp_path, "work_orders.json", {"work_orders": {WORK_ORDER_ID: work_order}}
        ),
        "valve_env": _write_runtime_json(
            tmp_path, "valve_env.json", _valve_environment()
        ),
        "generic_writer": _write_runtime_json(
            tmp_path, "generic_writer.json", payloads["generic_writer_dryrun_result"]
        ),
        "governed_shell": _write_runtime_json(
            tmp_path, "governed_shell.json", payloads["governed_shell_dryrun_result"]
        ),
        "holoindex": _write_runtime_json(
            tmp_path, "holoindex_evidence.json", payloads["holoindex_evidence"]
        ),
        "snapshots": _write_runtime_json(tmp_path, "snapshots.json", _snapshots()),
        "principals": _write_runtime_json(
            tmp_path, "principals.json", _principals(principal_public)
        ),
        "chain": tmp_path / "runtime" / "chain_results.json",
        "authority_state": tmp_path / "runtime" / "authority_state.json",
        "socket_path": tmp_path / "runtime" / "signer.sock",
    }
