'use strict';

const ALLOWED_KEYS = Object.freeze([
  'PATH', 'Path', 'SYSTEMROOT', 'SystemRoot', 'COMSPEC', 'ComSpec', 'PATHEXT',
  'TEMP', 'TMP', 'USERPROFILE', 'APPDATA', 'LOCALAPPDATA', 'PROGRAMDATA',
  'VIRTUAL_ENV',
  'OPENROUTER_API_KEY', 'FOUNDUPS_DB_PATH',
  'REDDOG_AUTHENTICATED_PRINCIPAL_ID', 'REDDOG_AUTHORIZED_FOUNDUP_IDS',
  'REDDOG_RESIDENT_ARCHITECT_FOUNDUP_ID',
  'REDDOG_RESIDENT_MODEL_RUNTIME_BINDING_ROOT',
  'REDDOG_READONLY_AUDIT_MODEL_RUNTIME_BINDING_RECEIPT_PATH',
  'REDDOG_BACKEND_ARCHITECT_MODEL_RUNTIME_BINDING_RECEIPT_PATH',
  'REDDOG_READONLY_AUDIT_MODEL_RUNTIME_BINDING_EXPECTED_RECEIPT_ID',
  'REDDOG_BACKEND_ARCHITECT_MODEL_RUNTIME_BINDING_EXPECTED_RECEIPT_ID',
  'REDDOG_AUTHORITATIVE_WORK_STATE_PATH',
  'REDDOG_PROVIDER_CALL_EVIDENCE_STORE_PATH',
  'REDDOG_EXTERNAL_RESEARCH_SNAPSHOT_PATH',
  'REDDOG_START_OPERATIONS_MAX_CLAIMS',
  'REDDOG_START_OPERATIONS_TIMEOUT_SECONDS',
  'REDDOG_READONLY_AUDIT_RUNTIME_MODE',
  'REDDOG_BACKEND_ARCHITECT_RUNTIME_MODE',
  'HOLOINDEX_SSD_PATH', 'HOLOINDEX_FRESHNESS_RECEIPT',
  'HOLOINDEX_QUERY_SERVICE_URL', 'HOLOINDEX_QUERY_SERVICE_TOKEN'
]);

function build(source) {
  const input = source && typeof source === 'object' ? source : {};
  const output = {};
  for (const key of ALLOWED_KEYS) {
    if (Object.prototype.hasOwnProperty.call(input, key)) output[key] = input[key];
  }
  output.PYTHONIOENCODING = 'utf-8';
  output.PYTHONUTF8 = '1';
  output.PYTHONNOUSERSITE = '1';
  return output;
}

module.exports = { ALLOWED_KEYS, build };
